// Friends vocabulary (142 words)
const SHOW_FRIENDS_WORDS = [
  { english: "forfeit", hebrew: "לאבד (זכות או רכוש) / לוותר", example: "If you break the rules, you will forfeit your security deposit." },
  { english: "waist", hebrew: "המותניים", example: "OR THE WAIST DOWN." },
  { english: "commencement", hebrew: "התחלה", example: "IN THE MIDDLE OF THE COMMENCEMENT ADDRESS." },
  { english: "flan", hebrew: "פלאן", example: "WE'RE HAVING BIRTHDAY FLAN." },
  { english: "goon", hebrew: "גון", example: "BECAUSE THAT'S WHERE THE PARTY IS, YOU GOON." },
  { english: "volleyball", hebrew: "כדורעף", example: "QUICK VOLLEYBALL QUESTION." },
  { english: "scotch", hebrew: "וויסקי", example: "WITH YOUR SCOTCH ON THE ROCKS IN A GLASS." },
  { english: "chimney", hebrew: "ארובה", example: "YEAH, LIKE A CHIMNEY." },
  { english: "moisten", hebrew: "לְרַטֵּט", example: "I WAS JUST MOISTENING THE TIP." },
  { english: "regiment", hebrew: "מְסוּדָּר", example: "ON A CAREFULLY REGIMENTED PROGRAM OF DENIAL..." },
  { english: "forefather", hebrew: "אבות", example: "OUR FOREFATHERS USED TO BITCH AT EACH OTHER?" },
  { english: "fabulous", hebrew: "נפלא", example: "YOU LOOK FABULOUS, HONEY, YOU REALLY DO." },
  { english: "rub", hebrew: "שפשף", example: "AND RUB THEM ALL OVER MY BODY." },
  { english: "phony", hebrew: "מְזוּיָף", example: "WHAT A PHONY." },
  { english: "quippy", hebrew: "מהנה", example: "I TEND TO GET A LITTLE DEFENDED AND QUIPPY?" },
  { english: "bassinet", hebrew: "סַלְטָר", example: "DO YOU SEE A LITTLE BASSINET IN THE CORNER?" },
  { english: "hound", hebrew: "כלבם", example: "LIKE A HOUND?" },
  { english: "hovercraft", hebrew: "רחפת", example: "I'M TALKING HOVERCRAFTS" },
  { english: "ap", hebrew: "ap", example: "AND APES TAKING OVER THE PLANET." },
  { english: "crawl", hebrew: "זחל", example: "I SAW THE WINDOW THAT I CRAWLED OUT OF AT MY WEDDING" },
  { english: "bridesmaid", hebrew: "השושבינות", example: "IT'S TIME. BRIDESMAIDS AND USHERS..." },
  { english: "usher", hebrew: "שומרים", example: "IT'S TIME. BRIDESMAIDS AND USHERS..." },
  { english: "syphilis", hebrew: "עגבת", example: "FROM THE SYPHILIS." },
  { english: "courage", hebrew: "אומץ", example: "THAT IT DID TAKE A LOT OF COURAGE" },
  { english: "wink", hebrew: "הִקְרִיץ", example: "THAT GIRL TOTALLY WINKED AT ME." },
  { english: "terrace", hebrew: "מרפסת", example: "OUT ON THE TERRACE..." },
  { english: "squeaky", hebrew: "צְרוּפִית", example: "AND ALL I COULD HEAR WAS LIKE THIS HIGH SQUEAKY SOUND" },
  { english: "blinking", hebrew: "מהבהב", example: "YOU LOOK ME IN THE EYE AND TELL ME WITHOUT BLINKING" },
  { english: "drain", hebrew: "לנקז", example: "OH, GOD, LOOK WHAT I FOUND IN THE DRAIN." },
  { english: "staring", hebrew: "בוהה", example: "STARING AT A PARKING METER." },
  { english: "meadow", hebrew: "מדו", example: "ALL RIGHT, SO, YOU'RE IN A MEADOW" },
  { english: "brook", hebrew: "פלג", example: "AND THE CALMING SOUNDS OF THE BABBLING BROOK..." },
  { english: "babbling", hebrew: "שְׂפַת־סָפָה", example: "AND THE CALMING SOUNDS OF THE BABBLING BROOK..." },
  { english: "cuddly", hebrew: "חמוד", example: "I THOUGHT YOU GUYS WERE CUDDLY SLEEPY." },
  { english: "drift", hebrew: "להיסחף", example: "TO DRIFT OFF, AND THEN YOU HUG HER" },
  { english: "dingy", hebrew: "מְלוּכָּלָה", example: "OLD AND DINGY, THAT'S ALL." },
  { english: "melt", hebrew: "התכה", example: "OKAY, SO, BY \"MELTING\" YOU MEANT MELTING." },
  { english: "fume", hebrew: "אדים", example: "I THINK THE FUMES ARE GIVING ME A HEADACHE." },
  { english: "charming", hebrew: "מקסים", example: "WELL, HE'S VERY CHARMING." },
  { english: "soberly", hebrew: "בְּצִנּוּת", example: "THAT I WOULD NEVER SOBERLY HURT YOU OR YOUR FAMILY." },
  { english: "eavesdropping", hebrew: "ציתות", example: "EAVESDROPPING? PHEEBS, THE CEILING TILES" },
  { english: "turtle", hebrew: "צבים", example: "TURTLES SCARE ME." },
  { english: "stripper", hebrew: "חשפנית", example: "IS SO HE CAN SEE A STRIPPER." },
  { english: "abridgment", hebrew: "קיצור", example: "THE ABRIDGEMENT." },
  { english: "goof", hebrew: "שִׁחְקוּק", example: "Oh, he's just goofing around." },
  { english: "vase", hebrew: "אגרטל", example: "\"THE EMPTY VASE." },
  { english: "translucent", hebrew: "שקוף", example: "TRANSLUCENT BEAUTY...\"" },
  { english: "confidante", hebrew: "סודנית", example: "HE'S BECOMING HER CONFIDANTE." },
  { english: "dense", hebrew: "צפוף", example: "WERE REALLY DENSE ABOUT POETRY?" },
  { english: "eclipse", hebrew: "כיסוי", example: "LIKE AN ECLIPSE." },
  { english: "log", hebrew: "יומן רישום", example: "OR AT LEAST WHAT I THOUGHT WAS A LOG." },
  { english: "trail", hebrew: "שביל", example: "YOU ALWAYS HAVE TO THINK ABOUT THE TRAIL!" },
  { english: "chop", hebrew: "קְצַת", example: "AND COULD YOU PLEASE CHOP SOME UP" },
  { english: "sauce", hebrew: "רוטב", example: "AND PUT IT RIGHT IN THE SAUCE?" },
  { english: "wire", hebrew: "חוט", example: "THE UNDER-WIRE FROM YOUR BRA." },
  { english: "loon", hebrew: "פריגטה", example: "OKAY, UM, YOU'RE A LOON, YOU KNOW?" },
  { english: "cranky", hebrew: "עצבני", example: "SHE WAS A CRUEL, CRANKY, OLD BITCH." },
  { english: "barrel", hebrew: "חבית", example: "WHEN I WAS A KID, I HAD A BARREL." },
  { english: "attic", hebrew: "עליית גג", example: "THAT'S THE GHOST FOR THE ATTIC." },
  { english: "sedative", hebrew: "תרופה מרגיעה", example: "TAKE A SEDATIVE." },
  { english: "maintenance", hebrew: "תחזוקה", example: "IS JUST, YOU KNOW, YOU'RE... KIND OF HIGH MAINTENANCE." },
  { english: "spat", hebrew: "ריב", example: "I THINK OUR LOVERS' SPAT" },
  { english: "bid", hebrew: "הצעה", example: "and then the highest bid gets it." },
  { english: "stepdad", hebrew: "אבא חורג", example: "and my stepdad would drag me around the backyard." },
  { english: "corny", hebrew: "נדוש", example: "Don't be so corny, Ross." },
  { english: "reindeer", hebrew: "אייל צפוני", example: "Santa has reindeers that can fly." },
  { english: "crib", hebrew: "עריסה", example: "Step away from the crib!" },
  { english: "stirring", hebrew: "לזוז", example: "Well, I heard Emma stirring," },
  { english: "blimp", hebrew: "ספינת אוויר", example: "Oh, please. Hit by a blimp?" },
  { english: "throw", hebrew: "להיזרק", example: "Sorry. I guess I was thrown off by the mention of my name." },
  { english: "pigeon", hebrew: "יונה", example: "and then a pigeon ate it." },
  { english: "grief", hebrew: "צער", example: "This about people not having a decent outlet for their grief." },
  { english: "fungus", hebrew: "פטריה", example: "Mucus, fungus, and the idea of me and Ross doing it." },
  { english: "mucus", hebrew: "נזלת", example: "Mucus, fungus, and the idea of me and Ross doing it." },
  { english: "oversee", hebrew: "לפקח", example: "to oversee all the kissing!" },
  { english: "haunted", hebrew: "רדוף", example: "some people are going to get seriously haunted." },
  { english: "mourner", hebrew: "מתאבל", example: "Oh, this is so exciting, my first mourner." },
  { english: "skittish", hebrew: "עצבני", example: "So excuse me for being a little skittish." },
  { english: "sweetheart", hebrew: "יקירי/יקירתי", example: "Good night, sweetheart. I love you." },
  { english: "wishbone", hebrew: "עצם משאלות", example: "Well, before, with the wishbone..." },
  { english: "beg", hebrew: "להתחנן", example: "I beg to differ." },
  { english: "lottery", hebrew: "לוטו", example: "Oh, the Powerball Lottery is up to $300 million" },
  { english: "pitch", hebrew: "להשתתף", example: "Why don't we all pitch in 50 bucks," },
  { english: "vanish", hebrew: "להיעלם", example: "The woman just vanished." },
  { english: "odd", hebrew: "סיכוי", example: "No. Do you know what your odds are of winning the lottery?" },
  { english: "tow", hebrew: "לגרור", example: "They're towing your car!" },
  { english: "casserole", hebrew: "תבשיל קדירה", example: "She dropped off a casserole." },
  { english: "piss", hebrew: "לבזבז", example: "I meant be cool and piss it all away." },
  { english: "spank", hebrew: "להעניש", example: "Is Daddy going to spank me?" },
  { english: "nightstand", hebrew: "שידת לילה", example: "There are no tickets on the nightstand." },
  { english: "bond", hebrew: "אג\"ח", example: "I'm going to put it all into a very low-yield bond." },
  { english: "squished", hebrew: "מעוך", example: "Valuable things are getting squished." },
  { english: "bra", hebrew: "חזייה", example: "Even these five that I hid in my bra." },
  { english: "cantaloupe", hebrew: "מלון קנטלופ", example: "but I think a cantaloupe might hurt less." },
  { english: "rehearse", hebrew: "לחזור על", example: "I'm rehearsing my lines." },
  { english: "inn", hebrew: "פונדק", example: "I'm taking Monica to a romantic inn in Vermont." },
  { english: "gorgeous", hebrew: "מדהים", example: "He is so gorgeous." },
  { english: "superb", hebrew: "מעולה", example: "The duck in particular was superb." },
  { english: "spleen", hebrew: "טחול", example: "♪ You can buy a human spleen ♪" },
  { english: "entertain", hebrew: "לבדר", example: "so I'm here to entertain." },
  { english: "dungeon", hebrew: "צינוק", example: "He was keeping my sister in a dungeon.\"" },
  { english: "complimentary", hebrew: "במתנה", example: "Could-could you have some complimentary toiletries" },
  { english: "toiletry", hebrew: "כלי רחצה", example: "Could-could you have some complimentary toiletries" },
  { english: "mouthwash", hebrew: "מי פה", example: "razor, mouthwash, deodorant," },
  { english: "razor", hebrew: "סכין גילוח", example: "razor, mouthwash, deodorant," },
  { english: "pepper", hebrew: "פלפל", example: "these great salt and pepper shakers" },
  { english: "shaker", hebrew: "מלחייה/פלפליה", example: "these great salt and pepper shakers" },
  { english: "think", hebrew: "לחשוב", example: "I wish I'd thought this through." },
  { english: "vault", hebrew: "כספת", example: "I'll ask the butler to fetch my diamonds out of the vault." },
  { english: "pretentious", hebrew: "יומרני", example: "your tiny portions of pretentious food?" },
  { english: "appetizer", hebrew: "מנה ראשונה", example: "\"I ordered the smoked salmon appetizer." },
  { english: "plug", hebrew: "אטם", example: "I'm wearing ear plugs." },
  { english: "clove", hebrew: "ציפורן", example: "Ear plugs? Or cloves of garlic?" },
  { english: "cone", hebrew: "אצטרובל", example: "But I-I want... I want the pine cones." },
  { english: "pretension", hebrew: "ימרנות", example: "and a little pretension never hurt anyone?" },
  { english: "incessant", hebrew: "בלתי פוסק", example: "but your evening was ruined by this incessant poll taking?" },
  { english: "peanut", hebrew: "בוטנים", example: "do you have peanut butter on the back of your head?" },
  { english: "butter", hebrew: "חמאת בוטנים", example: "do you have peanut butter on the back of your head?" },
  { english: "insemination", hebrew: "הזרעה", example: "the only other choice is insemination," },
  { english: "sperm", hebrew: "זרע", example: "so we're talking about sperm donors." },
  { english: "coaster", hebrew: "תחתיות", example: "Do you... do you have a coaster?" },
  { english: "tan", hebrew: "להשתזף", example: "Look at that woman sitting out by the pool getting tan." },
  { english: "clunk", hebrew: "להטיח", example: "I clunked your heads together." },
  { english: "non-racquet", hebrew: "יד לא אוחזת מחבט", example: "if at any time a player uses his non-racquet-bearing hand" },
  { english: "forfeit", hebrew: "לוותר", example: "to touch the playing surface, he or she forfeits the point." },
  { english: "musing", hebrew: "הרהור", example: "Musings, if you will." },
  { english: "eavesdrop", hebrew: "להקשיב בסתר", example: "I'm not going to eavesdrop on my friend." },
  { english: "bedspring", hebrew: "קפיץ מיטה", example: "Bedsprings... unmistakable." },
  { english: "enunciate", hebrew: "להגות", example: "Enunciate." },
  { english: "shellfish", hebrew: "רכיכות", example: "Y-You got shellfish in your head." },
  { english: "rattling", hebrew: "רעש", example: "( shells rattling )" },
  { english: "hum", hebrew: "לזמזם", example: "( humming )" },
  { english: "skull", hebrew: "גולגולת", example: "the shape of your skull before." },
  { english: "endeavor", hebrew: "מאמץ", example: "and wishes you the best of luck in all your endeavors." },
  { english: "wang", hebrew: "וואנג", example: "and let's face it, Mike's kind of a wang." },
  { english: "gnaw", hebrew: "לכרסם", example: "Yeah, I tried to gnaw myself free." },
  { english: "untangle", hebrew: "להתיר", example: "Now that I untangled you," },
  { english: "malfunctioning", hebrew: "תקלה", example: "So, a lot of malfunctioning wee-wees and hoo-hoos in this room, huh?" },
  { english: "raging", hebrew: "זועם", example: "My father is a raging alcoholic." },
  { english: "mitt", hebrew: "כפפה", example: "Ross, you don't even have oven mitts on." },
  { english: "sake", hebrew: "למען", example: "Well, just, you know, for argument's sake," },
  { english: "burp", hebrew: "גיהוק", example: "She's, she's the only one that knows how to burp the alphabet." },
];
