// Superstore vocabulary (119 words)
const SHOW_SUPERSTORE_WORDS = [
  { english: "reiterate", hebrew: "לחזור ולומר / לשנן", example: "Let me reiterate the main points of the agreement." },
  { english: "initiative", hebrew: "יוזמות", example: "for some green initiatives." },
  { english: "rip", hebrew: "rip", example: "would just rip into you like that." },
  { english: "gut", hebrew: "בטן", example: "I mean, that's got to be a gut punch." },
  { english: "reluctant", hebrew: "לֹא רוֹצֵה", example: "and I'm kind of like the-- I'm the reluctant leader." },
  { english: "shine", hebrew: "לזרוח", example: "♪ This little light of mine, I'm gonna let it shine ♪" },
  { english: "ram", hebrew: "RAM", example: "-I'll get the battering ram. -We have a battering ram?" },
  { english: "battering", hebrew: "לַהֲלוֹם", example: "-I'll get the battering ram. -We have a battering ram?" },
  { english: "plier", hebrew: "צבת", example: "Why, so you can pluck them out with your pliers?" },
  { english: "negate", hebrew: "לִשְׁלוֹל", example: "That doesn't negate all the good things" },
  { english: "labor", hebrew: "העבודה", example: "but labor of some sort." },
  { english: "masseuse", hebrew: "מעסה", example: "-We've got a masseuse… -[all] Ooh." },
  { english: "frisbees", hebrew: "פריזבי", example: "And we've got Cloud 9 Frisbees for the kids." },
  { english: "wage", hebrew: "שכר", example: "higher wages, and job security." },
  { english: "side", hebrew: "עקלתון", example: "I can't believe you're siding with corporate." },
  { english: "sophomore", hebrew: "סטוּדֶנט בִּשְׁנָתוֹ הָשְׁנִיָה", example: "and he's married to a sophomore." },
  { english: "teamster", hebrew: "נהג רכב", example: "I dated a Teamster, and he gets, like," },
  { english: "rot", hebrew: "נרקב", example: "If your skin was rotting, you would smell it, right?" },
  { english: "sneak", hebrew: "מתגנבת", example: "sneaking into a movie, they don't let you stay" },
  { english: "agitator", hebrew: "מסיתים", example: "We're trying to isolate the agitators." },
  { english: "earring", hebrew: "עגילים", example: "But then I realized that those earrings" },
  { english: "escalator", hebrew: "דְרַגנוֹעַ", example: "Uh, she fell off of an escalator," },
  { english: "detention", hebrew: "ריתוק", example: "once he gets out of detention," },
  { english: "unmatched", hebrew: "שֶׁאֵין כָּמוֹהוּ", example: "to customer service is unmatched," },
  { english: "scrub", hebrew: "לקרצף", example: "and scrub the walls." },
  { english: "ching", hebrew: "הסנטר", example: "No, no, no. I have a chin." },
  { english: "solid", hebrew: "מוצקים", example: "a standard exchange of solids." },
  { english: "silly", hebrew: "טיפשי", example: "No, no. That'd be silly." },
  { english: "oversold", hebrew: "עודף למעלה", example: "I oversold it, didn't I? I always do that." },
  { english: "commandeer", hebrew: "לְגַיֵס", example: "So I commandeered a corner of your desk here." },
  { english: "innocent", hebrew: "חף מפשע", example: "but maybe it's as innocent as it sounds." },
  { english: "serve", hebrew: "המגישה", example: "it's that I'm obsessed with serving the community." },
  { english: "lift", hebrew: "הרם", example: "we lift each other up." },
  { english: "charity", hebrew: "צדקה", example: "for a charity that's near and dear to my heart." },
  { english: "tot", hebrew: "כּוֹסִית", example: "I thought you meant tots like little people." },
  { english: "officiate", hebrew: "לְכַהֵן", example: "You want me to officiate at your wedding?" },
  { english: "fee", hebrew: "דמי", example: "For a small fee, we can get Tay Zonday." },
  { english: "transformer", hebrew: "רובוטריקים", example: "Excuse me, where do you keep your Transformers?" },
  { english: "puberty", hebrew: "גיל ההתבגרות", example: "Did you also want me to ask about the puberty?" },
  { english: "thrilling", hebrew: "מרתק", example: "I actually find shared secrets very thrilling." },
  { english: "thigh", hebrew: "הירכיים", example: "so she's trying to cut me off at the thighs." },
  { english: "insubordination", hebrew: "מַרדוּת", example: "I will write you up for insubordination." },
  { english: "warehouse", hebrew: "מחסן", example: "Jeanie! It's Marcus from the warehouse." },
  { english: "bald", hebrew: "קירח", example: "and I will not be bald for my wedding!" },
  { english: "wing", hebrew: "כנפיים", example: "Wings are on the way." },
  { english: "laxative", hebrew: "מְשַׁלשֵׁל", example: "They're filled with laxatives." },
  { english: "liver", hebrew: "הכבד", example: "I don't know. Where's my liver?" },
  { english: "lunatic", hebrew: "מטורף", example: "-I sound like a lunatic. -Yeah." },
  { english: "moisturize", hebrew: "לחות", example: "Remember to moisturize, okay?" },
  { english: "conscience", hebrew: "המצפון", example: "So your crisis of conscience" },
  { english: "bachelorette", hebrew: "רווקות", example: "-at the bachelorette? -Totally fake." },
  { english: "guard", hebrew: "המשמר", example: "I wanted you all to let your guard down." },
  { english: "explode", hebrew: "להתפוצץ", example: "the impact will make it explode." },
  { english: "rubberized", hebrew: "גומי", example: "The bottom's completely rubberized. Look at it." },
  { english: "tie", hebrew: "קשרו", example: "I love being stuck back here, tied to this wall." },
  { english: "whistling", hebrew: "שורק", example: "People are literally whistling while they work." },
  { english: "cereal", hebrew: "דגנים", example: "That cereal really changed the mood of this place." },
  { english: "pale", hebrew: "חיוור", example: "For me, it just pales in comparison" },
  { english: "scam", hebrew: "הונאה", example: "He's a scam artist." },
  { english: "bogus", hebrew: "מזויף", example: "He's been returning bogus items for months." },
  { english: "flip", hebrew: "התהפך", example: "Oh, you really flipped this little closet." },
  { english: "closet", hebrew: "בארון", example: "Oh, you really flipped this little closet." },
  { english: "plant", hebrew: "צמח", example: "Probably gonna have to take that plant outside for sun" },
  { english: "gossip", hebrew: "רכילות", example: "to the assistant gossip network." },
  { english: "slaughter", hebrew: "שחיטה", example: "for attempted cat-slaughter?" },
  { english: "lawsuit", hebrew: "התביעה", example: "Like, they're so afraid of a lawsuit," },
  { english: "herd", hebrew: "העדר", example: "I'm not one of the herd, Dina," },
  { english: "turd", hebrew: "צואה", example: "Herds are for turds." },
  { english: "thoughtful", hebrew: "מתחשב", example: "-That was very thoughtful. -I know." },
  { english: "seduce", hebrew: "לפתות", example: "At first, I was trying to seduce you" },
  { english: "compromise", hebrew: "פשרה", example: "and I'm not about to compromise my morals" },
  { english: "thunderstorm", hebrew: "סוּפַת רַעֲמִים", example: "it would probably feel like a thunderstorm in our pants." },
  { english: "pants", hebrew: "מכנסיים", example: "it would probably feel like a thunderstorm in our pants." },
  { english: "diabetes", hebrew: "סוכרת", example: "[shouting] Diabetes stinks!" },
  { english: "stink", hebrew: "מסריח", example: "[shouting] Diabetes stinks!" },
  { english: "shake", hebrew: "ניער", example: "Earl just shook an empty bowl at me and snapped his fingers." },
  { english: "snap", hebrew: "נשבר", example: "Earl just shook an empty bowl at me and snapped his fingers." },
  { english: "invasion", hebrew: "הפלישה", example: "Can we all talk about whether it's an invasion of privacy" },
  { english: "reiterate", hebrew: "לַחֲזוֹר וְלְשַׁנֵן", example: "So to reiterate, we must download an app that can" },
  { english: "giant", hebrew: "ענק", example: "I just don't love handing giant corporations a way" },
  { english: "surf", hebrew: "גלישה", example: "with her avatar surfing on a banana." },
  { english: "whip", hebrew: "השוט", example: "It's a meme of Indiana Jones cracking his whip." },
  { english: "hunch", hebrew: "התחושה", example: "I have a very good hunch." },
  { english: "circumcise", hebrew: "לָמוּל", example: "I think are circumcised?" },
  { english: "shoo", hebrew: "לירות", example: "[Glenn] Can we please try and shoo the toddlers away" },
  { english: "toddler", hebrew: "פעוטות", example: "[Glenn] Can we please try and shoo the toddlers away" },
  { english: "shrink", hebrew: "לכווץ", example: "We were number one in shrink reduction" },
  { english: "dull", hebrew: "משעמם", example: "Now the world just seems dull or something." },
  { english: "pharmacist", hebrew: "רוקח", example: "Move! Pharmacist coming through." },
  { english: "through", hebrew: "דרך", example: "Move! Pharmacist coming through." },
  { english: "room", hebrew: "חדר", example: "Step aside. I need room." },
  { english: "contraction", hebrew: "התכווצויות", example: "If the contractions are longer, that means you're in--" },
  { english: "birth", hebrew: "לידה", example: "Okay, look. I took part in a cow birth once." },
  { english: "cotton", hebrew: "כותנה", example: "I'll get cotton balls." },
  { english: "urge", hebrew: "הדחף", example: "you have an uncontrollable urge to push, okay?" },
  { english: "midwife", hebrew: "מְיַלֶדֶת", example: "I'm a trained midwife." },
  { english: "maneuver", hebrew: "תמרונים", example: "The company's targeted maneuvers" },
  { english: "ditch", hebrew: "לנטוש", example: "this good to ditch work." },
  { english: "kick", hebrew: "בעיטה", example: "-Did it kick? -No, I just--" },
  { english: "up", hebrew: "למעלה", example: "These meetings are worse from up here." },
  { english: "shot", hebrew: "ירה", example: "It's worth a shot, isn't it?" },
  { english: "welfare", hebrew: "רווחה", example: "You know, Cloud 9 is devoted to supporting the welfare" },
  { english: "beige", hebrew: "בז'", example: "Same stupid timecards. Same boring beige halls." },
  { english: "cockroach", hebrew: "מקק", example: "Actually, I think that cockroach in the light is new." },
  { english: "dock", hebrew: "עגינה", example: "or docking our pay for bathroom breaks?" },
  { english: "spot", hebrew: "ספוט", example: "Wow, that was spot on." },
  { english: "ranch", hebrew: "החווה", example: "beef products from Cloud 9 Ranch are now 80% off," },
  { english: "sharp", hebrew: "שארפ", example: "can I go to the doctor? I've had a sharp pain" },
  { english: "appendicitis", hebrew: "התוספתן", example: "that sounds like appendicitis." },
  { english: "bus", hebrew: "קורע", example: "You know, I've been busting my butt trying to show you" },
  { english: "butt", hebrew: "קת", example: "You know, I've been busting my butt trying to show you" },
  { english: "sparkling", hebrew: "נתזים", example: "I want this whole floor sparkling." },
  { english: "stumble", hebrew: "מְעִידָה", example: "I stumbled on the ladder and I fell into your hair." },
  { english: "gig", hebrew: "חלטורה", example: "you're looking for a gig, you know?" },
  { english: "pissed", hebrew: "מעוצבן", example: "God, I'm so pissed, Glenn." },
  { english: "applause", hebrew: "תְשׁוּאוֹת", example: "[applause]" },
  { english: "competent", hebrew: "המוסמכת", example: "They're so bad, they make Jonah look competent." },
  { english: "calm", hebrew: "רגוע", example: "Remember how calm he was on 9/11?" },
  { english: "two", hebrew: "שְׁנַיִם", example: "[high-pitched voice] \"Well, it's a two-way street, so… \"" },
];
