// Young Sheldon vocabulary (29 words)
const SHOW_YOUNG_SHELDON_WORDS = [
  { english: "badass", hebrew: "קשוח", example: "That was pretty badass, you walking out of class like that." },
  { english: "tweezers", hebrew: "פינצטה", example: "Wait, she has tweezers in her makeup bag." },
  { english: "pluck", hebrew: "לִקְטוֹף", example: "She plucks her eyebrows with them." },
  { english: "squirrel", hebrew: "סנאי", example: "that squirrel in your house?" },
  { english: "chlorine", hebrew: "כלור", example: "Do you smell like chlorine on purpose?" },
  { english: "garlic", hebrew: "שום", example: "and I promise I can make it garlic-free." },
  { english: "ringing", hebrew: "צלצול", example: "(phone ringing) Excuse me." },
  { english: "agitated", hebrew: "נסער", example: "I-It's Sheldon. He... sounds a little agitated." },
  { english: "clattering", hebrew: "מקשקשים", example: "(partition clattering loudly)" },
  { english: "loudly", hebrew: "בקול רם", example: "(partition clattering loudly)" },
  { english: "simultaneously", hebrew: "בו-זמנית", example: "So, you're really gonna date two men simultaneously?" },
  { english: "bulletin", hebrew: "עלון", example: "I need to run Sunday's bulletin" },
  { english: "counseling", hebrew: "ייעוץ", example: "I can't. The Walker couple is coming in for counseling." },
  { english: "applaud", hebrew: "לְשַׁבֵּחַ", example: "Well, I applaud the effort, young man." },
  { english: "subsidiary", hebrew: "לנציגות", example: "\"A subsidiary of the Domestic Food Corporation.\"" },
  { english: "cologne", hebrew: "קלן", example: "Do I have to sit downwind of Georgie's cologne?" },
  { english: "bum", hebrew: "בטלן", example: "There's a bum sleeping on our front porch." },
  { english: "porch", hebrew: "המרפסת", example: "There's a bum sleeping on our front porch." },
  { english: "mow", hebrew: "לכסח", example: "Why haven't you mowed the lawn?" },
  { english: "beverage", hebrew: "משקה", example: "Can I offer you a hot beverage?" },
  { english: "bonehead", hebrew: "טֶמבֶּל", example: "You're not an idiot. You're just a bonehead." },
  { english: "dump", hebrew: "לזרוק", example: "Kind of a dump." },
  { english: "homicide", hebrew: "רצח", example: "\"or seller's agent must disclose if a homicide" },
  { english: "slingshot", hebrew: "קלע", example: "is called the slingshot." },
  { english: "toe", hebrew: "בהונות", example: "flashing your toes at me." },
  { english: "flickering", hebrew: "הִבהוּב", example: "with a flickering light." },
  { english: "chest", hebrew: "חזה", example: "In the center of the room is a mysterious glowing chest." },
  { english: "sock", hebrew: "גרב", example: "Why was there a sock on your door?" },
  { english: "pry", hebrew: "לְחַטֵט", example: "-Shall I pry? -Uh, it's nothing." },
];
