// Emotions vocabulary (28 words)
const EMOTIONS_WORDS = [
  { english: "happy", hebrew: "שמח", example: "She felt happy when she saw her old friend at the party." },
  { english: "sad", hebrew: "עצוב", example: "He was sad after saying goodbye to his family." },
  { english: "angry", hebrew: "כועס", example: "The customer got angry when the store refused to give a refund." },
  { english: "anxious", hebrew: "חרד", example: "I feel anxious before every job interview." },
  { english: "excited", hebrew: "נרגש", example: "The children were excited about the trip to the amusement park." },
  { english: "afraid", hebrew: "מפוחד", example: "She was afraid of the dark as a child." },
  { english: "nervous", hebrew: "עצבני", example: "He felt nervous right before his big presentation." },
  { english: "jealous", hebrew: "מקנא", example: "He was jealous of his brother's new car." },
  { english: "proud", hebrew: "גאה", example: "The parents were proud of their daughter's graduation." },
  { english: "ashamed", hebrew: "מתבייש", example: "She felt ashamed after forgetting her friend's birthday." },
  { english: "embarrassed", hebrew: "נבוך", example: "I was embarrassed when I tripped in front of everyone." },
  { english: "grateful", hebrew: "אסיר תודה", example: "We are grateful for all the help you gave us." },
  { english: "lonely", hebrew: "בודד", example: "He felt lonely after moving to a new city." },
  { english: "confused", hebrew: "מבולבל", example: "The students were confused by the difficult math problem." },
  { english: "disgusted", hebrew: "נגעל", example: "She was disgusted by the smell coming from the fridge." },
  { english: "surprised", hebrew: "מופתע", example: "They were surprised by the sudden change in weather." },
  { english: "hopeful", hebrew: "מלא תקווה", example: "I'm hopeful that things will get better soon." },
  { english: "frustrated", hebrew: "מתוסכל", example: "He was frustrated when his computer kept crashing." },
  { english: "content", hebrew: "שבע רצון", example: "She felt content sitting by the fire with a good book." },
  { english: "overwhelmed", hebrew: "מוצף", example: "The new employee felt overwhelmed by all the tasks." },
  { english: "curious", hebrew: "סקרן", example: "The child was curious about how the toy worked." },
  { english: "relieved", hebrew: "מוקל", example: "I was relieved when I heard the test results were fine." },
  { english: "guilty", hebrew: "אשם", example: "He felt guilty for lying to his best friend." },
  { english: "bored", hebrew: "משועמם", example: "The students were bored during the long lecture." },
  { english: "calm", hebrew: "רגוע", example: "She stayed calm even during the stressful situation." },
  { english: "miserable", hebrew: "אומלל", example: "He felt miserable after losing his job." },
  { english: "delighted", hebrew: "מרוצה מאוד", example: "They were delighted with the surprise party." },
  { english: "terrified", hebrew: "מבועת", example: "She was terrified when she heard the loud noise at night." },
];
