// House vocabulary (55 words)
const HOUSE_WORDS = [
  { english: "attic", hebrew: "עליית גג", example: "The old books were stored in the attic." },
  { english: "banister", hebrew: "מעקה", example: "She held onto the banister as she climbed the stairs." },
  { english: "chimney", hebrew: "ארובה", example: "Smoke billowed from the chimney." },
  { english: "corridor", hebrew: "מסדרון", example: "The long corridor led to the classrooms." },
  { english: "cupboard", hebrew: "ארון", example: "The dishes are kept in the cupboard." },
  { english: "curtain", hebrew: "וילון", example: "She closed the curtains to block out the sunlight." },
  { english: "doorway", hebrew: "פתח", example: "He stood in the doorway, hesitating to enter." },
  { english: "drain", hebrew: "ניקוז", example: "The water went down the drain." },
  { english: "faucet", hebrew: "ברז", example: "Turn off the faucet when you're done brushing your teeth." },
  { english: "fence", hebrew: "גדר", example: "The wooden fence surrounded the garden." },
  { english: "floorboard", hebrew: "קרש רצפה", example: "The old floorboard creaked under his weight." },
  { english: "garage", hebrew: "מוסך", example: "The car is parked in the garage." },
  { english: "gutter", hebrew: "מרזב", example: "The leaves clogged the gutter." },
  { english: "hinge", hebrew: "ציר", example: "The rusty hinge squeaked when the door opened." },
  { english: "knob", hebrew: "ידית", example: "Turn the knob to open the door." },
  { english: "lawn", hebrew: "מדשאה", example: "The children played on the lawn." },
  { english: "porch", hebrew: "מרפסת כניסה", example: "We sat on the porch and watched the sunset." },
  { english: "shutter", hebrew: "תריס", example: "The shutters were closed to protect the windows from the storm." },
  { english: "staircase", hebrew: "גרם מדרגות", example: "The grand staircase led to the upper floors." },
  { english: "threshold", hebrew: "סף", example: "He paused at the threshold before entering the room." },
  { english: "windowsill", hebrew: " אדן החלון", example: "The cat sat on the windowsill, basking in the sun." },
  { english: "aisle", hebrew: "מעבר", example: "He walked down the aisle of the supermarket." },
  { english: "appliance", hebrew: "מכשיר חשמלי", example: "The kitchen is equipped with modern appliances." },
  { english: "awning", hebrew: "סוכך", example: "The awning provided shade on the patio." },
  { english: "beam", hebrew: "קורה", example: "The wooden beams supported the roof." },
  { english: "broom", hebrew: "מטאטא", example: "She swept the floor with a broom." },
  { english: "bulb", hebrew: "נורה", example: "The light bulb needs to be replaced." },
  { english: "cabinet", hebrew: "ארון (עם מדפים)", example: "The glasses are stored in the cabinet." },
  { english: "ceiling", hebrew: "תקרה", example: "The ceiling fan circulated the air." },
  { english: "cellar", hebrew: "מרתף", example: "The wine is kept in the cellar." },
  { english: "countertop", hebrew: "משטח עבודה", example: "She prepared the food on the kitchen countertop." },
  { english: "crate", hebrew: "ארגז", example: "The vegetables were shipped in wooden crates." },
  { english: "deck", hebrew: "סיפון", example: "We relaxed on the deck of the boat." },
  { english: "doorknob", hebrew: "ידית הדלת", example: "She turned the doorknob and entered the room." },
  { english: "driveway", hebrew: "שביל גישה", example: "The car pulled into the driveway." },
  { english: "fixture", hebrew: "גוף תאורה", example: "The light fixture illuminated the hallway." },
  { english: "furniture", hebrew: "רהיטים", example: "The living room was furnished with comfortable furniture." },
  { english: "hammer", hebrew: "פטיש", example: "He used a hammer to drive the nail into the wall." },
  { english: "hedge", hebrew: "גדר חיה", example: "The trimmed hedge formed a border around the property." },
  { english: "keyhole", hebrew: "חור המנעול", example: "She inserted the key into the keyhole." },
  { english: "ladder", hebrew: "סולם", example: "He climbed the ladder to reach the roof." },
  { english: "latch", hebrew: "בריח", example: "She lifted the latch and opened the gate." },
  { english: "mattress", hebrew: "מזרן", example: "The comfortable mattress ensured a good night's sleep." },
  { english: "outlet", hebrew: "שקע חשמלי", example: "Plug the lamp into the outlet." },
  { english: "pantry", hebrew: "מזווה", example: "The canned goods are stored in the pantry." },
  { english: "pillar", hebrew: "עמוד", example: "The marble pillars supported the temple." },
  { english: "rug", hebrew: "שטיח", example: "The colorful rug added warmth to the room." },
  { english: "saw", hebrew: "מסור", example: "He used a saw to cut the wood." },
  { english: "screw", hebrew: "בורג", example: "Tighten the screws to secure the shelf." },
  { english: "shed", hebrew: "סככה", example: "The gardening tools are kept in the shed." },
  { english: "sink", hebrew: "כיור", example: "Wash your hands in the sink." },
  { english: "socket", hebrew: "שקע", example: "He plugged the appliance into the socket." },
  { english: "stool", hebrew: "שרפרף", example: "He sat on the bar stool and ordered a drink." },
  { english: "terrace", hebrew: "מרפסת", example: "The restaurant had a lovely terrace overlooking the sea." },
  { english: "wallpaper", hebrew: "טפט", example: "The floral wallpaper brightened up the room." },
];
