// Kitchen vocabulary (62 words)
const KITCHEN_WORDS = [
  { english: "bland", hebrew: "תפל", example: "The chicken was a bit bland; it needed more seasoning." },
  { english: "boil", hebrew: "להרתיח", example: "You need to boil the water before adding the pasta." },
  { english: "broil", hebrew: "לצלות", example: "I'll broil the steak for a few minutes to give it a nice crust." },
  { english: "chop", hebrew: "לקצוץ", example: "She used a large knife to chop the vegetables for the soup." },
  { english: "dice", hebrew: "לחתוך לקוביות", example: "He will dice the onions into small, even pieces." },
  { english: "dough", hebrew: "בצק", example: "The baker kneaded the dough until it was smooth and elastic." },
  { english: "drain", hebrew: "לנקז", example: "Don't forget to drain the pasta before you put it in the bowl." },
  { english: "flavor", hebrew: "טעם", example: "This dish has a unique and complex flavor." },
  { english: "flour", hebrew: "קמח", example: "You'll need some flour to make the bread." },
  { english: "fry", hebrew: "לטגן", example: "We decided to fry the fish in a pan with some oil." },
  { english: "grate", hebrew: "לגרד", example: "He will grate the cheese over the spaghetti." },
  { english: "grease", hebrew: "לשמן", example: "Grease the pan with butter before you bake the cake." },
  { english: "herb", hebrew: "עשב תיבול", example: "Rosemary is my favorite herb to use with roasted potatoes." },
  { english: "knead", hebrew: "ללוש", example: "The recipe says to knead the dough for ten minutes." },
  { english: "ladle", hebrew: "מצקת", example: "She used a ladle to serve the hot soup into bowls." },
  { english: "marinate", hebrew: "להשרות במרינדה", example: "I'll marinate the chicken overnight to make it more tender." },
  { english: "mash", hebrew: "למעוך", example: "You can mash the potatoes with a fork or a special masher." },
  { english: "mince", hebrew: "לקצוץ דק", example: "The chef will mince the garlic very finely." },
  { english: "mix", hebrew: "לערבב", example: "Mix the sugar and flour together in a large bowl." },
  { english: "pan", hebrew: "מחבת", example: "He heated the oil in a frying pan on the stove." },
  { english: "peel", hebrew: "לקלף", example: "I always peel the carrots before I chop them." },
  { english: "pour", hebrew: "למזוג", example: "Please pour me a glass of water from the jug." },
  { english: "preheat", hebrew: "לחמם מראש", example: "Remember to preheat the oven to 350 degrees." },
  { english: "roast", hebrew: "לצלות", example: "We are going to roast a turkey for Thanksgiving dinner." },
  { english: "sauté", hebrew: "להקפיץ", example: "Sauté the mushrooms and onions until they are soft." },
  { english: "seasoning", hebrew: "תיבול", example: "This steak needs more salt and pepper for seasoning." },
  { english: "simmer", hebrew: "לבשל על אש קטנה", example: "Let the sauce simmer for 20 minutes to thicken." },
  { english: "slice", hebrew: "לפרוס", example: "She will slice the bread before we make sandwiches." },
  { english: "spatula", hebrew: "מרית", example: "Use a spatula to flip the pancakes in the pan." },
  { english: "spice", hebrew: "תבלין", example: "Curry is a blend of many different spices." },
  { english: "steam", hebrew: "לאדות", example: "It's healthier to steam the vegetables instead of frying them." },
  { english: "strain", hebrew: "לסנן", example: "You need to strain the broth to remove the solid pieces." },
  { english: "tender", hebrew: "רך", example: "The beef was so tender that it fell apart with a fork." },
  { english: "whisk", hebrew: "להקציף", example: "He used a whisk to beat the eggs until they were fluffy." },
  { english: "zest", hebrew: "גרידה", example: "The recipe calls for a little lemon zest to add flavor." },
  { english: "grill", hebrew: "לצלות על גריל", example: "We will grill some burgers in the backyard this evening." },
  { english: "bake", hebrew: "לאפות", example: "She loves to bake cakes and cookies for her family." },
  { english: "broth", hebrew: "ציר", example: "I made a rich chicken broth for the soup base." },
  { english: "casserole", hebrew: "תבשיל אפוי בתבנית", example: "My mom makes a delicious potato casserole for dinner." },
  { english: "cuisine", hebrew: "מטבח (סגנון בישול)", example: "French cuisine is known for its rich sauces and pastries." },
  { english: "garnish", hebrew: "לקשט", example: "The chef will garnish the plate with a sprig of parsley." },
  { english: "glaze", hebrew: "זיגוג", example: "She added a sweet honey glaze to the roasted carrots." },
  { english: "poach", hebrew: "לבשל בבישול עדין", example: "I like to poach an egg for my breakfast." },
  { english: "purée", hebrew: "למחית", example: "We can purée the cooked apples to make applesauce." },
  { english: "sieve", hebrew: "מסננת", example: "Use a sieve to sift the flour and sugar together." },
  { english: "appetizer", hebrew: "מתאבן / מנה ראשונה", example: "We ordered some calamari as an appetizer before the main course." },
  { english: "entrée", hebrew: "מנה עיקרית", example: "The steak is the main entrée on the menu tonight." },
  { english: "pastry", hebrew: "מאפה", example: "This bakery is famous for its sweet pastries." },
  { english: "poultry", hebrew: "עופות", example: "The restaurant offers a variety of poultry dishes, including chicken and duck." },
  { english: "soup", hebrew: "מרק", example: "A hot bowl of soup is perfect for a cold day." },
  { english: "salad", hebrew: "סלט", example: "A fresh green salad is a healthy side dish." },
  { english: "sauce", hebrew: "רוטב", example: "The pasta was topped with a rich tomato sauce." },
  { english: "dressing", hebrew: "רוטב לסלט", example: "I like a little olive oil and vinegar as a simple salad dressing." },
  { english: "sandwich", hebrew: "כריך", example: "He packed a turkey sandwich in his lunchbox." },
  { english: "spaghetti", hebrew: "ספגטי", example: "Spaghetti with meatballs is a classic Italian meal." },
  { english: "smoothie", hebrew: "שייק", example: "She makes a healthy smoothie with spinach and bananas every morning." },
  { english: "stew", hebrew: "נזיד", example: "The beef stew was slow-cooked for hours and was very tender." },
  { english: "condiment", hebrew: "תבלין", example: "Ketchup and mustard are common condiments for hot dogs." },
  { english: "omelet", hebrew: "חביתה", example: "For breakfast, she made a cheese and mushroom omelet." },
  { english: "juice", hebrew: "מיץ", example: "I prefer fresh orange juice to the kind from a carton." },
  { english: "cereal", hebrew: "דגני בוקר", example: "He eats a bowl of cereal with milk every day." },
  { english: "oatmeal", hebrew: "שיבולת שועל", example: "Oatmeal is a warm and hearty breakfast option." },
];
