// Travel vocabulary (39 words)
const TRAVEL_WORDS = [
  { english: "itinerary", hebrew: "מסלול טיול", example: "Our itinerary includes Paris, Rome, and Florence over two weeks." },
  { english: "customs", hebrew: "מכס", example: "You have to declare all goods to customs when entering the country." },
  { english: "layover", hebrew: "עצירת ביניים", example: "We have a three-hour layover in Dubai before the final flight." },
  { english: "visa", hebrew: "אשרת כניסה", example: "She had to apply for a tourist visa months before her trip." },
  { english: "border", hebrew: "גבול", example: "The train stopped at the border for a passport check." },
  { english: "exchange rate", hebrew: "שער חליפין", example: "Check the exchange rate before you convert your currency." },
  { english: "souvenir", hebrew: "מזכרת", example: "I bought a small statue as a souvenir of my visit." },
  { english: "commute", hebrew: "נסיעה יומית (לעבודה)", example: "His daily commute to the city takes over an hour." },
  { english: "terminal", hebrew: "טרמינל / בניין נוסעים", example: "Our flight departs from Terminal 3, Gate B12." },
  { english: "trek", hebrew: "מסע רגלי / טיול ארוך", example: "They embarked on a difficult trek through the Himalayas." },
  { english: "expedition", hebrew: "משלחת / מסע מחקר", example: "The scientific expedition explored the Amazon rainforest." },
  { english: "destination", hebrew: "יעד", example: "The Bahamas is a popular destination for honeymooners." },
  { english: "voucher", hebrew: "שובר", example: "We used a voucher to get a discount on the hotel room." },
  { english: "altitude", hebrew: "גובה (רום)", example: "Some hikers experience dizziness at high altitude." },
  { english: "glacier", hebrew: "קרחון", example: "We sailed to see the massive blue glacier up close." },
  { english: "harbor", hebrew: "נמל / מעגן", example: "The fishing boats returned to the harbor at sunset." },
  { english: "transit", hebrew: "מעבר / הובלה", example: "The city offers free public transit during the holidays." },
  { english: "landmark", hebrew: "ציון דרך / אתר מפורסם", example: "The Eiffel Tower is the most famous landmark in Paris." },
  { english: "bilingual", hebrew: "דו-לשוני", example: "It's helpful to have a bilingual guide in a foreign country." },
  { english: "passport", hebrew: "דרכון", example: "Don't forget to pack your passport and boarding pass." },
  { english: "luggage", hebrew: "מטען / כבודה", example: "We had to pay extra for overweight luggage." },
  { english: "shuttle", hebrew: "שאטל / הסעה", example: "The hotel provides a free shuttle to the airport." },
  { english: "ferry", hebrew: "מעבורת", example: "We took a ferry across the bay to the island." },
  { english: "inn", hebrew: "פונדק / בית הארחה קטן", example: "We stayed at a charming inn nestled in the mountains." },
  { english: "wilderness", hebrew: "שממה / אזור בראשיתי", example: "He spent two weeks hiking alone in the wilderness." },
  { english: "remote", hebrew: "מרוחק", example: "The village is located in a very remote area." },
  { english: "detour", hebrew: "עקיפה / דרך עוקפת", example: "The road closure forced us to take a detour." },
  { english: "lodging", hebrew: "לינה / מקום מגורים", example: "We booked cheap lodging near the city center." },
  { english: "canyon", hebrew: "קניון", example: "The Grand Canyon is one of nature's greatest sights." },
  { english: "jungle", hebrew: "ג'ונגל / יער גשם", example: "The guide led us safely through the thick jungle." },
  { english: "archipelago", hebrew: "ארכיפלג / קבוצת איים", example: "We sailed between the islands of the Greek archipelago." },
  { english: "caravan", hebrew: "שיירה / קרוואן", example: "The desert crossing was done by camel caravan." },
  { english: "reserve", hebrew: "שמורת טבע", example: "We visited a wildlife reserve to see the elephants." },
  { english: "altitude sickness", hebrew: "מחלת גבהים", example: "Drink lots of water to prevent altitude sickness." },
  { english: "gondola", hebrew: "גונדולה", example: "We took a gondola ride up the mountain for the view." },
  { english: "boulevard", hebrew: "שדרה רחבה", example: "The wide boulevard was lined with tall palm trees." },
  { english: "pavement", hebrew: "מדרכה / סלילה", example: "Be careful of cracks in the pavement while walking." },
  { english: "tourist trap", hebrew: "מלכודת תיירים", example: "That expensive restaurant near the square is a total tourist trap." },
  { english: "trekker", hebrew: "מטייל רגלי", example: "Experienced trekkers know how to pack light." },
];
