// Miscellaneous vocabulary not traced to a specific TV show (20 words)
const TVSHOWS_OTHER_WORDS = [
  { english: "commence", hebrew: "להתחיל / לפתוח ב-", example: "The ceremony will commence at exactly nine o'clock." },
  { english: "scrutinize", hebrew: "לבחון בדקדקנות", example: "The tax inspector will scrutinize all of your financial records." },
  { english: "convene", hebrew: "לכנס / להתכנס", example: "The committee will convene next week to discuss the budget." },
  { english: "elucidate", hebrew: "להבהיר / להסביר", example: "Could you please further elucidate your previous statement?" },
  { english: "vouch", hebrew: "לערב / להתחייב", example: "I can vouch for his honesty and professional skill." },
  { english: "apprehend", hebrew: "לעצור / לתפוס", example: "The police were able to apprehend the suspect near the station." },
  { english: "waive", hebrew: "לוותר על", example: "The bank agreed to waive the late payment fee this month." },
  { english: "reprimand", hebrew: "לנזוף", example: "The soldier was severely reprimanded for disobeying orders." },
  { english: "transcend", hebrew: "להתעלות על / לחרוג מ-", example: "His music transcends cultural and language barriers." },
  { english: "concede", hebrew: "להודות ב- / לוותר", example: "After a long debate, he finally had to concede defeat." },
  { english: "incur", hebrew: "לצבור / להיגרם", example: "The company incurred huge losses due to the product recall." },
  { english: "assess", hebrew: "להעריך / לאמוד", example: "The team needs to assess the risk before launch." },
  { english: "disseminate", hebrew: "להפיץ / לפזר (מידע)", example: "The news organization works to disseminate facts quickly." },
  { english: "allege", hebrew: "לטעון / להאשים", example: "The former employee alleges that the company engaged in fraud." },
  { english: "undermine", hebrew: "לחתור תחת / לערער", example: "Constant criticism can undermine a child's confidence." },
  { english: "mitigate", hebrew: "להקל / לשכך", example: "The insurance policy will mitigate the financial damage." },
  { english: "procure", hebrew: "להשיג / לרכוש", example: "The logistics team must procure all the necessary raw materials." },
  { english: "blaspheme", hebrew: "גידף", example: "The OR is a sacred place and I blasphemed it." },
  { english: "scythe", hebrew: "חרמש", example: "And that was my long scythe whispering to the ground" },
  { english: "strain", hebrew: "להתאמץ", example: "He strained his eyes by reading too much." },
];
