// TV Shows vocabulary (672 words)
const TVSHOWS_WORDS = [
  { english: "commence", hebrew: "להתחיל / לפתוח ב-", example: "The ceremony will commence at exactly nine o'clock." },
  { english: "scrutinize", hebrew: "לבחון בדקדקנות", example: "The tax inspector will scrutinize all of your financial records." },
  { english: "convene", hebrew: "לכנס / להתכנס", example: "The committee will convene next week to discuss the budget." },
  { english: "elucidate", hebrew: "להבהיר / להסביר", example: "Could you please further elucidate your previous statement?" },
  { english: "vouch", hebrew: "לערב / להתחייב", example: "I can vouch for his honesty and professional skill." },
  { english: "apprehend", hebrew: "לעצור / לתפוס", example: "The police were able to apprehend the suspect near the station." },
  { english: "waive", hebrew: "לוותר על", example: "The bank agreed to waive the late payment fee this month." },
  { english: "reiterate", hebrew: "לחזור ולומר / לשנן", example: "Let me reiterate the main points of the agreement." },
  { english: "reprimand", hebrew: "לנזוף", example: "The soldier was severely reprimanded for disobeying orders." },
  { english: "transcend", hebrew: "להתעלות על / לחרוג מ-", example: "His music transcends cultural and language barriers." },
  { english: "concede", hebrew: "להודות ב- / לוותר", example: "After a long debate, he finally had to concede defeat." },
  { english: "incur", hebrew: "לצבור / להיגרם", example: "The company incurred huge losses due to the product recall." },
  { english: "assess", hebrew: "להעריך / לאמוד", example: "The team needs to assess the risk before launch." },
  { english: "disseminate", hebrew: "להפיץ / לפזר (מידע)", example: "The news organization works to disseminate facts quickly." },
  { english: "allege", hebrew: "לטעון / להאשים", example: "The former employee alleges that the company engaged in fraud." },
  { english: "stipulate", hebrew: "לקבוע כתנאי / להכתיב", example: "The contract stipulates the exact terms of payment." },
  { english: "undermine", hebrew: "לחתור תחת / לערער", example: "Constant criticism can undermine a child's confidence." },
  { english: "mitigate", hebrew: "להקל / לשכך", example: "The insurance policy will mitigate the financial damage." },
  { english: "forfeit", hebrew: "לאבד (זכות או רכוש) / לוותר", example: "If you break the rules, you will forfeit your security deposit." },
  { english: "procure", hebrew: "להשיג / לרכוש", example: "The logistics team must procure all the necessary raw materials." },
  { english: "candor", hebrew: "כֵּנוּת", example: "I'm actually beginning to appreciate his candor." },
  { english: "triumph", hebrew: "ניצחון", example: "And I… I have my own kind of small triumph." },
  { english: "redemption", hebrew: "גאולה", example: "as some sort of act of redemption." },
  { english: "cadaver", hebrew: "גווייה", example: "This is not a cadaver. It's a father of three." },
  { english: "herniation", hebrew: "פריצת בקע", example: "If you don't, he can die of herniation." },
  { english: "revenge", hebrew: "נקמה", example: "He's out for revenge." },
  { english: "alienate", hebrew: "לגרום ניכור", example: "But, brother, you have managed to alienate" },
  { english: "shed", hebrew: "לשפוך", example: "And I don't want you to shed a single tear for me." },
  { english: "shack", hebrew: "פחון", example: "-[vehicle approaches] -I would rather live in a shack" },
  { english: "anesthesiologist", hebrew: "רופא מרדים", example: "Chastain used an out-of-network anesthesiologist" },
  { english: "hip", hebrew: "ירך", example: "Dr. Voss, the hip is all yours." },
  { english: "whistleblower", hebrew: "חושף שחיתות", example: "Hawkins is a whistleblower." },
  { english: "diligence", hebrew: "חריצות", example: "Take a guess how much your diligence cost this hospital today. No, allow me." },
  { english: "jogging", hebrew: "ריצה", example: "If he was jogging, had a fall," },
  { english: "curable", hebrew: "לריפוי", example: "It could be curable, Dr. Bell." },
  { english: "extradition", hebrew: "הסגרה", example: "Go hide out on an island somewhere without extradition laws to the U.S." },
  { english: "chill", hebrew: "צמרמורת", example: "And then I've been getting these chills." },
  { english: "presume", hebrew: "להניח", example: "Do not presume to know my mind." },
  { english: "seldom", hebrew: "לעתים רחוקות", example: "It was a family matter, seldom spoken about," },
  { english: "maim", hebrew: "נכה", example: "The doctor maimed her and it did no good." },
  { english: "uppermost", hebrew: "עליון", example: "what is uppermost in your mind." },
  { english: "bruise", hebrew: "חבורה", example: "There's a… There's a nasty bruise on Henry's arm." },
  { english: "embrace", hebrew: "חיבוק", example: "Embrace me!" },
  { english: "freak", hebrew: "השתגע", example: "-and I freaked out. -Mmm." },
  { english: "transplant", hebrew: "השתלה", example: "and it is my heart, but it's not because of my transplant." },
  { english: "dizzy", hebrew: "מסוחרר", example: "He's been tired, weak, dizzy, and some of his joints are swollen." },
  { english: "blast", hebrew: "פיצוץ", example: "Oh, my mistake. That sounds like a blast." },
  { english: "meek", hebrew: "ענו", example: "\"Blessed are the meek.\"" },
  { english: "blaspheme", hebrew: "גידף", example: "The OR is a sacred place and I blasphemed it." },
  { english: "bandage", hebrew: "תחבושות", example: "He's stolen all of the bandages, except one." },
  { english: "rib", hebrew: "צלעות", example: "right about where your ribs meet?" },
  { english: "lung", hebrew: "ריאות", example: "my lungs exploding." },
  { english: "parathyroidectomy", hebrew: "כריתת בלוטת התריס", example: "Ah, Mr. Levine's parathyroidectomy. How was that?" },
  { english: "malnourishment", hebrew: "תת תזונה", example: "Yes, I'm showing signs of severe malnourishment," },
  { english: "sabotage", hebrew: "לחבל", example: "Don't sabotage a career that's just beginning." },
  { english: "hypotension", hebrew: "לחץ דם נמוך", example: "Hypotension, JVD," },
  { english: "whistle", hebrew: "שריקה", example: "-Where did the whistle come from? -Now!" },
  { english: "abhorrent", hebrew: "נָתוּן לְשִׂנְאָה", example: "Michael, the way men behave on dating apps is abhorrent." },
  { english: "procrastinating", hebrew: "מתמהמה", example: "You're procrastinating. This will speed things along." },
  { english: "pottery", hebrew: "קדרות", example: "He's so stun, and he teaches a pottery class nearby. Check him out." },
  { english: "gooey", hebrew: "דביק", example: "when their wet gooey fingers start intertwining in sludgy, sinful ecstasy." },
  { english: "sparkle", hebrew: "נצנוץ", example: "Stay that way, don't let them take your sparkle." },
  { english: "malfeasance", hebrew: "מעילה", example: "\"Malfeasance\"?" },
  { english: "beanie", hebrew: "כובע צמר", example: "He's not a robber. He's just a straight guy in a stupid beanie." },
  { english: "upheaval", hebrew: "מהפך", example: "No, Grant, the Tower card represents disaster, upheaval, and danger." },
  { english: "awash", hebrew: "שטוף", example: "Her face awash in golden light" },
  { english: "initiative", hebrew: "יוזמות", example: "for some green initiatives." },
  { english: "rip", hebrew: "rip", example: "would just rip into you like that." },
  { english: "gut", hebrew: "בטן", example: "I mean, that's got to be a gut punch." },
  { english: "reluctant", hebrew: "לֹא רוֹצֵה", example: "and I'm kind of like the-- I'm the reluctant leader." },
  { english: "shine", hebrew: "לזרוח", example: "♪ This little light of mine, I'm gonna let it shine ♪" },
  { english: "ram", hebrew: "RAM", example: "-I'll get the battering ram. -We have a battering ram?" },
  { english: "battering", hebrew: "לַהֲלוֹם", example: "-I'll get the battering ram. -We have a battering ram?" },
  { english: "plier", hebrew: "צבת", example: "Why, so you can pluck them out with your pliers?" },
  { english: "negate", hebrew: "לִשְׁלוֹל", example: "That doesn't negate all the good things" },
  { english: "labor", hebrew: "העבודה", example: "but labor of some sort." },
  { english: "masseuse", hebrew: "מעסה", example: "-We've got a masseuse… -[all] Ooh." },
  { english: "frisbees", hebrew: "פריזבי", example: "And we've got Cloud 9 Frisbees for the kids." },
  { english: "wage", hebrew: "שכר", example: "higher wages, and job security." },
  { english: "side", hebrew: "עקלתון", example: "I can't believe you're siding with corporate." },
  { english: "sophomore", hebrew: "סטוּדֶנט בִּשְׁנָתוֹ הָשְׁנִיָה", example: "and he's married to a sophomore." },
  { english: "teamster", hebrew: "נהג רכב", example: "I dated a Teamster, and he gets, like," },
  { english: "rot", hebrew: "נרקב", example: "If your skin was rotting, you would smell it, right?" },
  { english: "sneak", hebrew: "מתגנבת", example: "sneaking into a movie, they don't let you stay" },
  { english: "agitator", hebrew: "מסיתים", example: "We're trying to isolate the agitators." },
  { english: "earring", hebrew: "עגילים", example: "But then I realized that those earrings" },
  { english: "escalator", hebrew: "דְרַגנוֹעַ", example: "Uh, she fell off of an escalator," },
  { english: "detention", hebrew: "ריתוק", example: "once he gets out of detention," },
  { english: "unmatched", hebrew: "שֶׁאֵין כָּמוֹהוּ", example: "to customer service is unmatched," },
  { english: "scrub", hebrew: "לקרצף", example: "and scrub the walls." },
  { english: "shining", hebrew: "נוצץ", example: "♪ His bright shining star ♪" },
  { english: "sermon", hebrew: "הדרשה", example: "of the sermon that I've chosen for you tonight." },
  { english: "abide", hebrew: "לְהִשָׁאֵר", example: "No, I couldn't abide it and I wouldn't." },
  { english: "fretting", hebrew: "דאגה", example: "You've been set on it since winter, so there's no point fretting now." },
  { english: "orphan", hebrew: "יתומים", example: "I haven't got any more orphans concealed hereabouts." },
  { english: "concealed", hebrew: "מוסתר", example: "I haven't got any more orphans concealed hereabouts." },
  { english: "hereabout", hebrew: "כָּאן בָּסְבִיבָה", example: "I haven't got any more orphans concealed hereabouts." },
  { english: "asylum", hebrew: "מקלט", example: "took an orphan boy out of the asylum," },
  { english: "burn", hebrew: "שרוף", example: "And they nearly burnt to a crisp in their beds!" },
  { english: "crisp", hebrew: "קריספ", example: "And they nearly burnt to a crisp in their beds!" },
  { english: "qualm", hebrew: "נְקִיפַת מַצְפּוּן", example: "I've had some qualms myself." },
  { english: "fearful", hebrew: "חוֹשֵׁשׁ", example: "and the whole family died in fearful agonies." },
  { english: "agony", hebrew: "הייסורים", example: "and the whole family died in fearful agonies." },
  { english: "delight", hebrew: "יישמחו", example: "but I shall always call it \"the White Way of Delight.\"" },
  { english: "thrill", hebrew: "הריגוש", example: "I-I know because of the thrill." },
  { english: "grub", hebrew: "grub", example: "to see those ugly white grubs spade up in the cucumber beds." },
  { english: "cucumber", hebrew: "מלפפון", example: "to see those ugly white grubs spade up in the cucumber beds." },
  { english: "vex", hebrew: "לְהַקְנִיט", example: "Mr. and Mrs. Hammond were certainly vexed all the time." },
  { english: "geese", hebrew: "אווזים", example: "They choose each other out of all the other geese in the world," },
  { english: "incapable", hebrew: "לֹא מְסוּגָל", example: "Do you consider yourself to be delicate and incapable? Because I certainly don't." },
  { english: "delicate", hebrew: "עדין", example: "Do you consider yourself to be delicate and incapable? Because I certainly don't." },
  { english: "notion", hebrew: "מושגים", example: "And put those fool notions out of your head." },
  { english: "fool", hebrew: "לשטות", example: "And put those fool notions out of your head." },
  { english: "ching", hebrew: "הסנטר", example: "No, no, no. I have a chin." },
  { english: "solid", hebrew: "מוצקים", example: "a standard exchange of solids." },
  { english: "silly", hebrew: "טיפשי", example: "No, no. That'd be silly." },
  { english: "bliss", hebrew: "בליס", example: "♪ Oh, what joyful bliss ♪" },
  { english: "coat", hebrew: "המעילים", example: "♪ Coats and hats and such as that ♪" },
  { english: "thermal", hebrew: "תרמי", example: "♪ And thermal underwear ♪" },
  { english: "compassion", hebrew: "חמלה", example: "♪ Love and compassion ♪" },
  { english: "caroler", hebrew: "קרולר", example: "♪ Gifts exchanged and carolers sing ♪" },
  { english: "flame", hebrew: "להבה", example: "as the flame gets closer, and closer, and closer," },
  { english: "pinch", hebrew: "צובט", example: "I was pinching myself a lot today to prove that this was all true." },
  { english: "despair", hebrew: "ייאוש", example: "I'm in the depths of despair." },
  { english: "lump", hebrew: "לאמפ", example: "When you try to eat, a big lump comes right up into your throat," },
  { english: "undress", hebrew: "להפשיט", example: "[exhales] Well, undress. Quick as you can. Get to bed." },
  { english: "sob", hebrew: "לְהִתיַפֵּחַ", example: "[sobs]" },
  { english: "filthy", hebrew: "המטונפות", example: "Oh, that is a filthy habit!" },
  { english: "daresay", hebrew: "מעז", example: "Daresay a man's got a right to smoke..." },
  { english: "kettle", hebrew: "קומקום", example: "Yes, this is certainly a fine kettle of fish." },
  { english: "pity", hebrew: "מרחם", example: "Well, now, it... seems a pity." },
  { english: "dispatch", hebrew: "מוקד", example: "No, she's gotta be dispatched straightway back where she came from." },
  { english: "chirping", hebrew: "צִיוּץ", example: "[birds chirping]" },
  { english: "rooster", hebrew: "רוסטר", example: "[rooster crows, cows mooing]" },
  { english: "crow", hebrew: "עורבים", example: "[rooster crows, cows mooing]" },
  { english: "mooing", hebrew: "Moo", example: "[rooster crows, cows mooing]" },
  { english: "bleat", hebrew: "לִפְעוֹת", example: "[goats bleating]" },
  { english: "cherish", hebrew: "מוקיר", example: "shall cherish this gift always." },
  { english: "devotion", hebrew: "מסירות", example: "-Let my kiss prove my devotion. -[Marilla] What are you doing?" },
  { english: "harvest", hebrew: "הקציר", example: "to see if that French boy is available through harvest." },
  { english: "seagull", hebrew: "שחפים", example: "[seagulls squawking]" },
  { english: "squawking", hebrew: "לְקַעֲקֵעַ", example: "[seagulls squawking]" },
  { english: "heroine", hebrew: "הגיבורה", example: "Because it sounds so romantic, as if I were a heroine in a storybook." },
  { english: "fever", hebrew: "קדחת", example: "They died of a fever when I was three months old." },
  { english: "burden", hebrew: "הנטל", example: "If children are such a burden, then why do people have so many of them?" },
  { english: "wiry", hebrew: "דקיק", example: "I don't know, but the wiry ones are the best after all." },
  { english: "gracious", hebrew: "אדיב", example: "Gracious heavenly Father..." },
  { english: "numerous", hebrew: "רבים", example: "And as for the things I want, they're so numerous" },
  { english: "heathen", hebrew: "עוֹבֵד אֵלִילִים", example: "That girl's next door to a perfect heathen." },
  { english: "cluck", hebrew: "לְקַרְקֵר", example: "[clucks]" },
  { english: "silverware", hebrew: "כְּלֵי כֶּסֶף", example: "I'll check the silverware." },
  { english: "sleeve", hebrew: "שרוולים", example: "Puff sleeves are divine." },
  { english: "divine", hebrew: "אלוהי", example: "Puff sleeves are divine." },
  { english: "fabric", hebrew: "בד", example: "-Waste of fabric. -Oh." },
  { english: "temper", hebrew: "המזג", example: "in such a terrible display of temper as we've just seen?" },
  { english: "embarrass", hebrew: "נבוך", example: "and embarrassed you in front of Mrs. Lynde." },
  { english: "ponder", hebrew: "להרהר", example: "I'm sorry for worrying you. I needed time to ponder." },
  { english: "contrite", hebrew: "חרטה", example: "I appreciate that you're contrite, Anne..." },
  { english: "astonish", hebrew: "לְהַדהִים", example: "-Wish I'd been there. -Matthew Cuthbert, I'm astonished at you." },
  { english: "fibb", hebrew: "שקרים", example: "If I apologize, I'll be fibbing." },
  { english: "dreadful", hebrew: "נורא", example: "a dreadful determined woman, dreadful determined." },
  { english: "determined", hebrew: "נחוש", example: "a dreadful determined woman, dreadful determined." },
  { english: "lonesome", hebrew: "רבדים", example: "It's terrible lonesome downstairs without you." },
  { english: "humiliating", hebrew: "משפיל", example: "The trouble is that the prospect seems humiliating and unfair." },
  { english: "benefactor", hebrew: "נַדבָן", example: "I shall always remember that you were a benefactor--" },
  { english: "graciousness", hebrew: "אדיבות", example: "-Thank you for your graciousness. -Of course." },
  { english: "thoroughly", hebrew: "ביסודיות", example: "I thought since I had to do it, I might as well do it thoroughly." },
  { english: "tidy", hebrew: "מסודר", example: "You look clean and tidy, and that's what counts." },
  { english: "treasured", hebrew: "אוצר", example: "This is a treasured possession. Do you understand?" },
  { english: "bequeath", hebrew: "הוריש", example: "My mother bequeathed it to me." },
  { english: "reticent", hebrew: "מְאוּפָּק", example: "I'm less shy than reticent." },
  { english: "needlepoint", hebrew: "רקמה", example: "I like reading, too, but Mother prefers that I do needlepoint." },
  { english: "swear", hebrew: "נשבע", example: "Shall we swear to be best friends forever and ever?" },
  { english: "oath", hebrew: "שבועה", example: "-And then we sent our oath into the world. -Not in the..." },
  { english: "confess", hebrew: "להתוודות", example: "Confess at once." },
  { english: "brooch", hebrew: "הסיכה", example: "I told you that brooch meant a great deal to me." },
  { english: "oversold", hebrew: "עודף למעלה", example: "I oversold it, didn't I? I always do that." },
  { english: "commandeer", hebrew: "לְגַיֵס", example: "So I commandeered a corner of your desk here." },
  { english: "innocent", hebrew: "חף מפשע", example: "but maybe it's as innocent as it sounds." },
  { english: "illusion", hebrew: "אשליות", example: "♪ With illusions of someday ♪" },
  { english: "cast", hebrew: "הליהוק", example: "♪ Casting a golden light ♪" },
  { english: "barn", hebrew: "האסם", example: "Uh, continue with the barn work. Stack some wood in the kitchen. I have to go!" },
  { english: "rig", hebrew: "מעטה", example: "-Take the rig back in. -Yes, ma'am." },
  { english: "ma", hebrew: "גברתי", example: "-Take the rig back in. -Yes, ma'am." },
  { english: "torment", hebrew: "לַעֲנוֹת", example: "My years of torment and uncertainty are behind me." },
  { english: "convey", hebrew: "להעביר", example: "I am, indeed. So if you wouldn't mind conveying me towards my new life?" },
  { english: "serve", hebrew: "המגישה", example: "it's that I'm obsessed with serving the community." },
  { english: "lift", hebrew: "הרם", example: "we lift each other up." },
  { english: "charity", hebrew: "צדקה", example: "for a charity that's near and dear to my heart." },
  { english: "tot", hebrew: "כּוֹסִית", example: "I thought you meant tots like little people." },
  { english: "officiate", hebrew: "לְכַהֵן", example: "You want me to officiate at your wedding?" },
  { english: "fee", hebrew: "דמי", example: "For a small fee, we can get Tay Zonday." },
  { english: "transformer", hebrew: "רובוטריקים", example: "Excuse me, where do you keep your Transformers?" },
  { english: "figgy", hebrew: "תאנים", example: "forgot to put figs in her figgy pudding!" },
  { english: "marching", hebrew: "צועדים", example: "The marching does kind of give it away." },
  { english: "precious", hebrew: "יקרות", example: "-Bye-bye, precious girl. -[laughs] Yay." },
  { english: "fertility", hebrew: "פוריות", example: "Getting fertility treatments is better than anything that comes in paper." },
  { english: "treatment", hebrew: "טיפולים", example: "Getting fertility treatments is better than anything that comes in paper." },
  { english: "funeral", hebrew: "הלוויה", example: "Haven't seen you since your father's funeral six months ago." },
  { english: "jurisdiction", hebrew: "השיפוט", example: "♪ It's in my jurisdiction To hand you this eviction ♪" },
  { english: "hefty", hebrew: "הצהרותיהם", example: "♪ You'll also get a hefty check To cut down on the friction ♪" },
  { english: "friction", hebrew: "חיכוך", example: "♪ You'll also get a hefty check To cut down on the friction ♪" },
  { english: "jolly", hebrew: "העליז", example: "♪ 'Tis the season to be jolly By golly, I'm down with this ♪" },
  { english: "vacate", hebrew: "פינוי", example: "♪ Here's a notice to vacate And a check to relocate ♪" },
  { english: "occasion", hebrew: "אירוע", example: "I've just always wanted to say that, but the occasion never seemed quite right." },
  { english: "withdraw", hebrew: "לסגת", example: "♪ So take your money now Or withdraw it daily ♪" },
  { english: "checker", hebrew: "בודק", example: "♪ My checkered past won't let me be ♪" },
  { english: "farewell", hebrew: "פרידה", example: "♪ Say farewell to Christmas ♪" },
  { english: "feast", hebrew: "משתה", example: "♪ Some have feasts upon their tables ♪" },
  { english: "crumb", hebrew: "פירורי", example: "♪ Others only crumbs ♪" },
  { english: "reproach", hebrew: "תוכחה", example: "Your ministry and your vision for this town are both beyond reproach." },
  { english: "vow", hebrew: "הנדרים", example: "There were no buts in our wedding vows." },
  { english: "revolve", hebrew: "סובבת", example: "♪ My world revolves around you ♪" },
  { english: "storm", hebrew: "סופות", example: "♪ I pray we can weather What storms come our way ♪" },
  { english: "pillow", hebrew: "הכרית", example: "♪ My soft pillow ♪" },
  { english: "assure", hebrew: "מבטיח", example: "♪ And I can assure you ♪" },
  { english: "adore", hebrew: "מעריצה", example: "♪ And I so adore you ♪" },
  { english: "rearview", hebrew: "מראה אחורית", example: "and then this town will be in my rearview mirror." },
  { english: "parade", hebrew: "מצעד", example: "♪ Complaining and a-raining On everyone's parade ♪" },
  { english: "blow", hebrew: "לפוצץ", example: "♪ But what you're doing now Is such a low blow ♪" },
  { english: "demolish", hebrew: "להרוס", example: "♪ Demolishing the lives Of all the people you know ♪" },
  { english: "deed", hebrew: "דידס", example: "But words and deeds can slay!" },
  { english: "slay", hebrew: "לחסל", example: "But words and deeds can slay!" },
  { english: "regret", hebrew: "מתחרט", example: "♪ You'll live to regret it ♪" },
  { english: "demeanor", hebrew: "הֲלִיכוֹת", example: "♪ Oh, Regina, I have seen A lot of change in your demeanor ♪" },
  { english: "scheme", hebrew: "הִתנַכְּלוּת", example: "♪ Scheming is your new arena ♪" },
  { english: "arena", hebrew: "ארנה", example: "♪ Scheming is your new arena ♪" },
  { english: "fierce", hebrew: "אכזרית", example: "♪ Girl, you think you're so fierce! ♪" },
  { english: "needle", hebrew: "המחט", example: "Guess I don't need a needle to get my ears pierced." },
  { english: "pierce", hebrew: "פירסינג", example: "Guess I don't need a needle to get my ears pierced." },
  { english: "grumble", hebrew: "לִנְהוֹם", example: "♪ Hey, oh, you just grumble and scoff ♪" },
  { english: "scoff", hebrew: "לֶאֱפוֹז", example: "♪ Hey, oh, you just grumble and scoff ♪" },
  { english: "oughta", hebrew: "צריך", example: "♪ You oughta know, you oughta know You oughta know, oh, oh ♪" },
  { english: "folk", hebrew: "חברים", example: "♪ A little bit of kindness For the folks below ♪" },
  { english: "royal", hebrew: "המלכותי", example: "♪ So get off your royal highness And save this town ♪" },
  { english: "highness", hebrew: "הוד מעלתך", example: "♪ So get off your royal highness And save this town ♪" },
  { english: "mean", hebrew: "מתכוון", example: "♪ The queen of mean ♪" },
  { english: "astray", hebrew: "שֶׁלֹא בָּדֶרֶך הַיָשָׁר", example: "♪ Lest someone should go astray ♪" },
  { english: "lest", hebrew: "שמא", example: "♪ Lest someone should go astray ♪" },
  { english: "fan", hebrew: "מאוורר", example: "♪ Fan the flames with all your might ♪" },
  { english: "glow", hebrew: "זוהר", example: "it was clear from the glow of the lamps where the lamplighter had been." },
  { english: "lamplighter", hebrew: "מנורת מנורה", example: "it was clear from the glow of the lamps where the lamplighter had been." },
  { english: "beacon", hebrew: "משואת", example: "♪ Be a beacon in the night ♪" },
  { english: "mankind", hebrew: "המין האנושי", example: "♪ Be a blessing to mankind ♪" },
  { english: "light", hebrew: "הדליק", example: "Your father lit a path for you to follow." },
  { english: "hallucination", hebrew: "הזיה", example: "Well, I'm glad you're just a hallucination" },
  { english: "oyster", hebrew: "צדפות", example: "[woman 2] Bags of oysters! Bags of oysters!" },
  { english: "preoccupied", hebrew: "מוטרד", example: "Well, I was too preoccupied to eat." },
  { english: "espionage", hebrew: "ריגול", example: "Oh! Right! Espionage." },
  { english: "ferry", hebrew: "המעבורת", example: "The ferry. I can't miss it!" },
  { english: "matron", hebrew: "אֵם הַבַּיִת", example: "-I must speak with the matron. -The matron? She's not even awake." },
  { english: "rouse", hebrew: "לְעוֹרֵר", example: "Come inside. I'll see if I can rouse the matron." },
  { english: "recitation", hebrew: "דקלום", example: "May I interest you in a poetic recitation spoken aloud with dignified emotion?" },
  { english: "dignified", hebrew: "מכובד", example: "May I interest you in a poetic recitation spoken aloud with dignified emotion?" },
  { english: "bother", hebrew: "מטריד", example: "This man is indeed bothering me." },
  { english: "supper", hebrew: "הסעודה", example: "Please take your things up to your room. I'll get supper on." },
  { english: "puberty", hebrew: "גיל ההתבגרות", example: "Did you also want me to ask about the puberty?" },
  { english: "thrilling", hebrew: "מרתק", example: "I actually find shared secrets very thrilling." },
  { english: "thigh", hebrew: "הירכיים", example: "so she's trying to cut me off at the thighs." },
  { english: "insubordination", hebrew: "מַרדוּת", example: "I will write you up for insubordination." },
  { english: "warehouse", hebrew: "מחסן", example: "Jeanie! It's Marcus from the warehouse." },
  { english: "bald", hebrew: "קירח", example: "and I will not be bald for my wedding!" },
  { english: "wing", hebrew: "כנפיים", example: "Wings are on the way." },
  { english: "laxative", hebrew: "מְשַׁלשֵׁל", example: "They're filled with laxatives." },
  { english: "liver", hebrew: "הכבד", example: "I don't know. Where's my liver?" },
  { english: "lunatic", hebrew: "מטורף", example: "-I sound like a lunatic. -Yeah." },
  { english: "moisturize", hebrew: "לחות", example: "Remember to moisturize, okay?" },
  { english: "conscience", hebrew: "המצפון", example: "So your crisis of conscience" },
  { english: "bachelorette", hebrew: "רווקות", example: "-at the bachelorette? -Totally fake." },
  { english: "guard", hebrew: "המשמר", example: "I wanted you all to let your guard down." },
  { english: "explode", hebrew: "להתפוצץ", example: "the impact will make it explode." },
  { english: "rubberized", hebrew: "גומי", example: "The bottom's completely rubberized. Look at it." },
  { english: "tie", hebrew: "קשרו", example: "I love being stuck back here, tied to this wall." },
  { english: "whistling", hebrew: "שורק", example: "People are literally whistling while they work." },
  { english: "entrust", hebrew: "להפקיד", example: "♪ It's all been entrusted to me ♪" },
  { english: "treasure", hebrew: "אוצר", example: "♪ I treasure these memories ♪" },
  { english: "purchase", hebrew: "רכישה", example: "♪ You can purchase them all ♪" },
  { english: "sunshine", hebrew: "סאנשיין", example: "♪ A girl bright as sunshine ♪" },
  { english: "escort", hebrew: "ליווי", example: "♪ Asked to escort her ♪" },
  { english: "litter", hebrew: "המלטה", example: "Hasn't anyone ever taught you it's not nice to litter the Earth?" },
  { english: "snoop", hebrew: "סנופ", example: "So you're lazy and a snoop." },
  { english: "tear", hebrew: "קרוע", example: "But Rachel Lynde told Mother that Miss Cuthbert was torn asunder after you left." },
  { english: "asunder", hebrew: "לִקְרָעִים", example: "But Rachel Lynde told Mother that Miss Cuthbert was torn asunder after you left." },
  { english: "sorrowful", hebrew: "עָצוּב", example: "It's hard to believe she was sorrowful when she doesn't seem to like me at all." },
  { english: "wick", hebrew: "רשעים", example: "\"If all the world hated you, and believed you wicked," },
  { english: "absolve", hebrew: "לִפְטוֹר", example: "while your own conscience approved of you, and absolved you from guilt," },
  { english: "guilt", hebrew: "אשמה", example: "while your own conscience approved of you, and absolved you from guilt," },
  { english: "confound", hebrew: "הִמוּם", example: "Confounding, indeed. I hope those old Cuthberts aren't losing their marbles." },
  { english: "marble", hebrew: "גולות", example: "Confounding, indeed. I hope those old Cuthberts aren't losing their marbles." },
  { english: "addled", hebrew: "מְבוּלבָּל", example: "I mean, I hope they aren't becoming addled, dear, as seniors are wont to do." },
  { english: "parlor", hebrew: "לטרקלין", example: "Please come down to the parlor." },
  { english: "solemnity", hebrew: "חֲגִיגִיוּת", example: "I believe that this is a matter of much solemnity." },
  { english: "fondness", hebrew: "חִבָּה", example: "I could develop a fondness for this." },
  { english: "cereal", hebrew: "דגנים", example: "That cereal really changed the mood of this place." },
  { english: "pale", hebrew: "חיוור", example: "For me, it just pales in comparison" },
  { english: "scam", hebrew: "הונאה", example: "He's a scam artist." },
  { english: "bogus", hebrew: "מזויף", example: "He's been returning bogus items for months." },
  { english: "flip", hebrew: "התהפך", example: "Oh, you really flipped this little closet." },
  { english: "closet", hebrew: "בארון", example: "Oh, you really flipped this little closet." },
  { english: "plant", hebrew: "צמח", example: "Probably gonna have to take that plant outside for sun" },
  { english: "gossip", hebrew: "רכילות", example: "to the assistant gossip network." },
  { english: "slaughter", hebrew: "שחיטה", example: "for attempted cat-slaughter?" },
  { english: "lawsuit", hebrew: "התביעה", example: "Like, they're so afraid of a lawsuit," },
  { english: "herd", hebrew: "העדר", example: "I'm not one of the herd, Dina," },
  { english: "turd", hebrew: "צואה", example: "Herds are for turds." },
  { english: "thoughtful", hebrew: "מתחשב", example: "-That was very thoughtful. -I know." },
  { english: "seduce", hebrew: "לפתות", example: "At first, I was trying to seduce you" },
  { english: "compromise", hebrew: "פשרה", example: "and I'm not about to compromise my morals" },
  { english: "thunderstorm", hebrew: "סוּפַת רַעֲמִים", example: "it would probably feel like a thunderstorm in our pants." },
  { english: "pants", hebrew: "מכנסיים", example: "it would probably feel like a thunderstorm in our pants." },
  { english: "diabetes", hebrew: "סוכרת", example: "[shouting] Diabetes stinks!" },
  { english: "stink", hebrew: "מסריח", example: "[shouting] Diabetes stinks!" },
  { english: "shake", hebrew: "ניער", example: "Earl just shook an empty bowl at me and snapped his fingers." },
  { english: "snap", hebrew: "נשבר", example: "Earl just shook an empty bowl at me and snapped his fingers." },
  { english: "invasion", hebrew: "הפלישה", example: "Can we all talk about whether it's an invasion of privacy" },
  { english: "reiterate", hebrew: "לַחֲזוֹר וְלְשַׁנֵן", example: "So to reiterate, we must download an app that can" },
  { english: "giant", hebrew: "ענק", example: "I just don't love handing giant corporations a way" },
  { english: "surf", hebrew: "גלישה", example: "with her avatar surfing on a banana." },
  { english: "whip", hebrew: "השוט", example: "It's a meme of Indiana Jones cracking his whip." },
  { english: "portentous", hebrew: "מבשר רעות", example: "Please let that not be portentous." },
  { english: "broom", hebrew: "מטאטא", example: "I'll fetch a broom." },
  { english: "salutation", hebrew: "ברכה", example: "Salutations." },
  { english: "hunch", hebrew: "התחושה", example: "I have a very good hunch." },
  { english: "slandered", hebrew: "לְהַשְׁמִיץ", example: "-You want to get slandered? -Sorry. I truly meant no harm. I..." },
  { english: "nasty", hebrew: "מגעיל", example: "There, there. That nasty girl didn't know any better." },
  { english: "orchard", hebrew: "הבוסתן", example: "They're from our orchard. They're real sweet." },
  { english: "aggrieved", hebrew: "פגועים", example: "My daughter is sorely aggrieved." },
  { english: "sorely", hebrew: "מְאוֹד", example: "My daughter is sorely aggrieved." },
  { english: "outrage", hebrew: "זעם", example: "This outrage will not be forgotten by anyone anytime soon." },
  { english: "pardon", hebrew: "החנינה", example: "-How would you know? -I beg your pardon?" },
  { english: "trollop", hebrew: "פרוצה", example: "You didn't do Avonlea any favors bringing that... trollop into our midst." },
  { english: "midst", hebrew: "אֶמצַע", example: "You didn't do Avonlea any favors bringing that... trollop into our midst." },
  { english: "bleak", hebrew: "עגום", example: "For some bleak pittance e'er compelled to roam" },
  { english: "pittance", hebrew: "פרוטות", example: "For some bleak pittance e'er compelled to roam" },
  { english: "compelled", hebrew: "נֶאֱלָץ", example: "For some bleak pittance e'er compelled to roam" },
  { english: "roam", hebrew: "לנדוד", example: "For some bleak pittance e'er compelled to roam" },
  { english: "cheer", hebrew: "לעודד", example: "Few hearts to cheer him through his dangerous life" },
  { english: "companion", hebrew: "לוויה", example: "Companion of the sea and silent air" },
  { english: "scarce", hebrew: "נדיר", example: "\"Without the comfort, hope, with scarce a friend" },
  { english: "circumcise", hebrew: "לָמוּל", example: "I think are circumcised?" },
  { english: "plain", hebrew: "רגיל", example: "♪ Even though you're strange and plain ♪" },
  { english: "fraternize", hebrew: "לְהִתיַדֵד", example: "They are not to fraternize in any manner at any time." },
  { english: "transpire", hebrew: "לְהִתְרַחֵשׁ", example: "for all that has transpired." },
  { english: "contamination", hebrew: "זיהום", example: "I must preserve my Diana from the contamination" },
  { english: "exert", hebrew: "לְהַפְעִיל", example: "You are not to fraternize, or exert undue influence." },
  { english: "undue", hebrew: "מוּפרָז", example: "You are not to fraternize, or exert undue influence." },
  { english: "spoil", hebrew: "מפונקת", example: "You've gone and spoiled the child, Matthew." },
  { english: "fortunate", hebrew: "ברי מזל", example: "I must say it was fortunate that you knew what to do." },
  { english: "humble", hebrew: "צנוע", example: "May I enter your humble abode?" },
  { english: "abode", hebrew: "מָקוֹם", example: "May I enter your humble abode?" },
  { english: "prattl", hebrew: "לְקַשְׁקֵשׁ", example: "You girls have been prattling on for hours about nothing." },
  { english: "fate", hebrew: "גורל", example: "what it is your fate to be required to bear.\"" },
  { english: "intrude", hebrew: "פולש", example: "We're sorry to intrude, but we wanted you to have that." },
  { english: "scorn", hebrew: "בוז", example: "Why wasn't it possible? Were you a woman scorned?" },
  { english: "mortgage", hebrew: "משכנתא", example: "[Marilla] You mortgaged the farm? Are you out of your mind?" },
  { english: "paradise", hebrew: "גן עדן", example: "I've truly found paradise here at Green Gables." },
  { english: "glorious", hebrew: "המפוארת", example: "Isn't it glorious?" },
  { english: "temptation", hebrew: "פיתוי", example: "Sorry. The temptation was irresistible." },
  { english: "irresistible", hebrew: "מפתה", example: "Sorry. The temptation was irresistible." },
  { english: "quandary", hebrew: "מְבוּכָה", example: "I'm in a moral quandary." },
  { english: "scythe", hebrew: "חרמש", example: "And that was my long scythe whispering to the ground" },
  { english: "frequent", hebrew: "תכופים", example: "He frequents the pub down the block." },
  { english: "crop", hebrew: "יבולים", example: "Tell me, should your father simply give his crops away" },
  { english: "sting", hebrew: "עוקץ", example: "It's a bumblebee nickname. It's cute, but it stings." },
  { english: "yell", hebrew: "צועקים", example: "I wanna just say sorry for yelling at you." },
  { english: "stir", hebrew: "מערבבים", example: "She stirs the pot. She's a pot stirrer." },
  { english: "pot", hebrew: "סיר", example: "She stirs the pot. She's a pot stirrer." },
  { english: "tattoo", hebrew: "קעקועים", example: "I don't want to expose my tattoos." },
  { english: "appetite", hebrew: "התיאבון", example: "and that doesn't affect your appetite?" },
  { english: "pouty", hebrew: "מרושל", example: "You know, the blond with the pouty," },
  { english: "remnant", hebrew: "השריד", example: "A small, fading remnant of a star." },
  { english: "dwarf", hebrew: "הגמד", example: "A white dwarf. That's right." },
  { english: "density", hebrew: "צפיפות", example: "and it has the density of 40 suns." },
  { english: "tension", hebrew: "המתח", example: "Will they or won't they? Sexual tension." },
  { english: "will", hebrew: "יהיה", example: "Will they or won't they? Sexual tension." },
  { english: "sort", hebrew: "למיין", example: "That's sort of my gimmick." },
  { english: "damper", hebrew: "מַנחֵת", example: "didn't put a damper on the trip." },
  { english: "shoo", hebrew: "לירות", example: "[Glenn] Can we please try and shoo the toddlers away" },
  { english: "toddler", hebrew: "פעוטות", example: "[Glenn] Can we please try and shoo the toddlers away" },
  { english: "shrink", hebrew: "לכווץ", example: "We were number one in shrink reduction" },
  { english: "dull", hebrew: "משעמם", example: "Now the world just seems dull or something." },
  { english: "pharmacist", hebrew: "רוקח", example: "Move! Pharmacist coming through." },
  { english: "through", hebrew: "דרך", example: "Move! Pharmacist coming through." },
  { english: "room", hebrew: "חדר", example: "Step aside. I need room." },
  { english: "contraction", hebrew: "התכווצויות", example: "If the contractions are longer, that means you're in--" },
  { english: "birth", hebrew: "לידה", example: "Okay, look. I took part in a cow birth once." },
  { english: "cotton", hebrew: "כותנה", example: "I'll get cotton balls." },
  { english: "urge", hebrew: "הדחף", example: "you have an uncontrollable urge to push, okay?" },
  { english: "midwife", hebrew: "מְיַלֶדֶת", example: "I'm a trained midwife." },
  { english: "maneuver", hebrew: "תמרונים", example: "The company's targeted maneuvers" },
  { english: "ditch", hebrew: "לנטוש", example: "this good to ditch work." },
  { english: "kick", hebrew: "בעיטה", example: "-Did it kick? -No, I just--" },
  { english: "up", hebrew: "למעלה", example: "These meetings are worse from up here." },
  { english: "shot", hebrew: "ירה", example: "It's worth a shot, isn't it?" },
  { english: "welfare", hebrew: "רווחה", example: "You know, Cloud 9 is devoted to supporting the welfare" },
  { english: "beige", hebrew: "בז'", example: "Same stupid timecards. Same boring beige halls." },
  { english: "cockroach", hebrew: "מקק", example: "Actually, I think that cockroach in the light is new." },
  { english: "dock", hebrew: "עגינה", example: "or docking our pay for bathroom breaks?" },
  { english: "spot", hebrew: "ספוט", example: "Wow, that was spot on." },
  { english: "ranch", hebrew: "החווה", example: "beef products from Cloud 9 Ranch are now 80% off," },
  { english: "sharp", hebrew: "שארפ", example: "can I go to the doctor? I've had a sharp pain" },
  { english: "appendicitis", hebrew: "התוספתן", example: "that sounds like appendicitis." },
  { english: "bus", hebrew: "קורע", example: "You know, I've been busting my butt trying to show you" },
  { english: "butt", hebrew: "קת", example: "You know, I've been busting my butt trying to show you" },
  { english: "sparkling", hebrew: "נתזים", example: "I want this whole floor sparkling." },
  { english: "consent", hebrew: "הסכמה", example: "My life will only be complete if you consent to our marriage." },
  { english: "mischief", hebrew: "שובבות", example: "And don't get up to any mischief!" },
  { english: "chatter", hebrew: "פטפוט", example: "[background chatter]" },
  { english: "veil", hebrew: "רעלה", example: "-[Anne] Prissy, do you have a bridal veil? -I'm going to be wearing my mother's." },
  { english: "poverty", hebrew: "עוני", example: "It's sad and unlawful and full of poverty and--" },
  { english: "resemble", hebrew: "דומים", example: "People who resemble me." },
  { english: "faint", hebrew: "התעלף", example: "-What happened? -You fainted." },
  { english: "apprentice", hebrew: "החניך", example: "Do you need an apprentice?" },
  { english: "craft", hebrew: "מלאכה", example: "you could help me craft my study plan? I promise I won't keep fainting." },
  { english: "invigorating", hebrew: "מְעוֹדֵד", example: "Ah, this little vacation is absolutely invigorating." },
  { english: "scatter", hebrew: "מפוזרים", example: "Our family legacies scattered on the wind." },
  { english: "pawnbroker", hebrew: "מַשׁכּוֹנַאי", example: "Anne said the pawnbroker's a powerful negotiator." },
  { english: "reclaim", hebrew: "לְטַיֵב", example: "You reclaimed it." },
  { english: "bestow", hebrew: "לְהַעֲנִיק", example: "And later, it will be your gift to bestow on someone you love." },
  { english: "whisper", hebrew: "לוחש", example: "[Mr. Phillips whispering] Prissy?" },
  { english: "murmuring", hebrew: "לְרַנֵן", example: "[murmurings]" },
  { english: "indistinctly", hebrew: "באופן לא ברור", example: "[man speaks indistinctly]" },
  { english: "stumble", hebrew: "מְעִידָה", example: "I stumbled on the ladder and I fell into your hair." },
  { english: "gig", hebrew: "חלטורה", example: "you're looking for a gig, you know?" },
  { english: "pissed", hebrew: "מעוצבן", example: "God, I'm so pissed, Glenn." },
  { english: "applause", hebrew: "תְשׁוּאוֹת", example: "[applause]" },
  { english: "competent", hebrew: "המוסמכת", example: "They're so bad, they make Jonah look competent." },
  { english: "calm", hebrew: "רגוע", example: "Remember how calm he was on 9/11?" },
  { english: "insult", hebrew: "תעליב", example: "The poll taxes were the final insult" },
  { english: "mint", hebrew: "מנטה", example: "the royal jewels or even the coin in the mint." },
  { english: "traitor", hebrew: "בוגדים", example: "What they really wanted were the traitors who had imposed the poll tax." },
  { english: "imposed", hebrew: "הטילה", example: "What they really wanted were the traitors who had imposed the poll tax." },
  { english: "kidnap", hebrew: "לחטוף", example: "and trying to kidnap the Prime Minister." },
  { english: "salvation", hebrew: "הישועה", example: "where they hid in the chapel and prayed for salvation." },
  { english: "chapel", hebrew: "קפלת", example: "where they hid in the chapel and prayed for salvation." },
  { english: "priest", hebrew: "הכומר", example: "(PRIEST PRAYING)" },
  { english: "refuge", hebrew: "מקלט", example: "had taken refuge in the Tower," },
  { english: "decapitate", hebrew: "לַעֲרוֹף רֹאשׁ", example: "He was dragged out to Tower Hill and decapitated." },
  { english: "nail", hebrew: "מסמר", example: "with his bishop's miter nailed on for good measure." },
  { english: "miter", hebrew: "מִצנֶפֶת", example: "with his bishop's miter nailed on for good measure." },
  { english: "gang", hebrew: "כנופיה", example: "For a gang of ordinary peasants to take, what was basically" },
  { english: "fortress", hebrew: "מבצר", example: "in the greatest fortress in the land and hack his head off on Tower Hill" },
  { english: "peril", hebrew: "הסכנה", example: "Well, you antagonize the mob at your peril, but it was also a reminder" },
  { english: "menacing", hebrew: "מאיים", example: "and regained its reputation as a menacing fortress." },
  { english: "notorious", hebrew: "הידוע לשמצה", example: "of one of Britain's most notorious and mysterious crimes." },
  { english: "riddle", hebrew: "רידל", example: "This is a riddle worthy of any detective novel." },
  { english: "custody", hebrew: "משמורת", example: "quickly took them into his custody, and placed them in the Tower of London." },
  { english: "nephew", hebrew: "האחיינים", example: "his nephews had vanished completely." },
  { english: "portray", hebrew: "לְתַאֵר", example: "who portrayed him as an evil, hunchbacked, crown-stealing murderer." },
  { english: "start", hebrew: "לְהַרתִיעַ", example: "Then, suddenly, startling new evidence was turned up," },
  { english: "torture", hebrew: "עינויים", example: "There are no dungeons here, there's not even a torture chamber." },
  { english: "reputation", hebrew: "המוניטין", example: "But in the Tudor years, the Tower earned a new reputation." },
  { english: "execute", hebrew: "תבוצע", example: "It was a place where people were sent to be executed." },
  { english: "manly", hebrew: "גברי", example: "you need to know about Henry's self-image. It's big, it's manly, it's virile." },
  { english: "virile", hebrew: "גַברִי", example: "you need to know about Henry's self-image. It's big, it's manly, it's virile." },
  { english: "grumpy", hebrew: "מְמוּרמָר", example: "when he was fat, and grumpy, and ill, and tyrannical." },
  { english: "tyrannical", hebrew: "רוֹדָנִי", example: "when he was fat, and grumpy, and ill, and tyrannical." },
  { english: "doom", hebrew: "אבדון", example: "edged slowly towards his doom," },
  { english: "devout", hebrew: "אדוק", example: "On the one hand he was a devout Catholic." },
  { english: "verdict", hebrew: "פסק דין", example: "His accusers deliberated for just 15 minutes before giving their verdict." },
  { english: "contemplate", hebrew: "לְהַרהֵר", example: "More was sent back to this room to contemplate his awful fate." },
  { english: "awful", hebrew: "נורא", example: "More was sent back to this room to contemplate his awful fate." },
  { english: "leisure", hebrew: "פנאי", example: "\"and dear charity hath no leisure" },
  { english: "frighten", hebrew: "להפחיד", example: "The Tower was built to frighten and subjugate them." },
  { english: "subjugate", hebrew: "לַעֲשׁוֹק", example: "The Tower was built to frighten and subjugate them." },
  { english: "landscape", hebrew: "נוף", example: "castles have shaped Britain's famous landscape." },
  { english: "villain", hebrew: "נבלים", example: "to some of the greatest heroes and villains in our national history." },
  { english: "intrigue", hebrew: "תככים", example: "-treachery, intrigue and even murder. -(SWORDS CLANKING)" },
  { english: "treachery", hebrew: "בְּגִידָה", example: "-treachery, intrigue and even murder. -(SWORDS CLANKING)" },
  { english: "cliff", hebrew: "הצוקים", example: "This imposing fortress on the white cliffs of Dover" },
  { english: "plaster", hebrew: "טיח", example: "is plastered in the names of people who've stopped in here for a pint." },
  { english: "unarmed", hebrew: "לֹא מְזוּיָן", example: "JONES: They found Becket unarmed in his cathedral." },
  { english: "atrocity", hebrew: "זְוָעָה", example: "It was an atrocity that shook 12th-century Europe." },
  { english: "saint", hebrew: "סנט", example: "Two years later, Becket was a saint, but Henry was a hate figure." },
  { english: "barefoot", hebrew: "יחפה", example: "Henry turned up at Canterbury, barefoot and dressed in sackcloth robes." },
  { english: "sackcloth", hebrew: "לְבוּשׁ שַׂק", example: "Henry turned up at Canterbury, barefoot and dressed in sackcloth robes." },
  { english: "rob", hebrew: "גלימות", example: "Henry turned up at Canterbury, barefoot and dressed in sackcloth robes." },
  { english: "shrine", hebrew: "מקדש", example: "From this point on, Becket's shrine became Europe's number one tourist destination" },
  { english: "pilgrim", hebrew: "צליינים", example: "visited by pilgrims from all over the continent." },
  { english: "grand", hebrew: "גרנד", example: "and Henry had to put on some kind of grand show." },
  { english: "humiliation", hebrew: "השפלה", example: "And perhaps because of that humiliation, within a couple of months," },
  { english: "excommunicated", hebrew: "לְהַחרִים", example: "The rebel barons were excommunicated and England erupted into civil war." },
  { english: "siege", hebrew: "המצור", example: "a siege technology known as undermining." },
  { english: "frustrate", hebrew: "מתוסכל", example: "JONES: On the 14th of October, 1216, frustrated by three long months of siege," },
  { english: "truce", hebrew: "הַפסָקַת אֵשׁ", example: "Louis negotiated a truce." },
  { english: "vessel", hebrew: "כלי", example: "so what you needed were the smaller vessels to go into the beach," },
  { english: "troops", hebrew: "חיילים", example: "pick up the troops from the beach and ferry them back to the larger ships." },
  { english: "preliminary", hebrew: "ראשוני", example: "I'd like to have a preliminary powwow," },
  { english: "powwow", hebrew: "דִיוּן", example: "I'd like to have a preliminary powwow," },
  { english: "conundrum", hebrew: "חידה", example: "our library's back door conundrum." },
  { english: "emasculat", hebrew: "לְסַרֵס", example: "Do you people have any idea how emasculating that is?" },
  { english: "brunet", hebrew: "ברונטית", example: "Mmm. Who is the lucky brunette?" },
  { english: "thing", hebrew: "דברים", example: "Well, I try to keep things where they should be." },
  { english: "badass", hebrew: "קשוח", example: "That was pretty badass, you walking out of class like that." },
  { english: "tweezers", hebrew: "פינצטה", example: "Wait, she has tweezers in her makeup bag." },
  { english: "pluck", hebrew: "לִקְטוֹף", example: "She plucks her eyebrows with them." },
  { english: "squirrel", hebrew: "סנאי", example: "that squirrel in your house?" },
  { english: "chlorine", hebrew: "כלור", example: "Do you smell like chlorine on purpose?" },
  { english: "garlic", hebrew: "שום", example: "and I promise I can make it garlic-free." },
  { english: "affection", hebrew: "חיבה", example: "Now, we may not feel God's protection, affection, and connection right now," },
  { english: "chuckle", hebrew: "לְצַחְקֵק", example: "[Billy chuckles]" },
  { english: "ringing", hebrew: "צלצול", example: "(phone ringing) Excuse me." },
  { english: "agitated", hebrew: "נסער", example: "I-It's Sheldon. He... sounds a little agitated." },
  { english: "clattering", hebrew: "מקשקשים", example: "(partition clattering loudly)" },
  { english: "loudly", hebrew: "בקול רם", example: "(partition clattering loudly)" },
  { english: "two", hebrew: "שְׁנַיִם", example: "[high-pitched voice] \"Well, it's a two-way street, so… \"" },
  { english: "simultaneously", hebrew: "בו-זמנית", example: "So, you're really gonna date two men simultaneously?" },
  { english: "bulletin", hebrew: "עלון", example: "I need to run Sunday's bulletin" },
  { english: "counseling", hebrew: "ייעוץ", example: "I can't. The Walker couple is coming in for counseling." },
  { english: "applaud", hebrew: "לְשַׁבֵּחַ", example: "Well, I applaud the effort, young man." },
  { english: "subsidiary", hebrew: "לנציגות", example: "\"A subsidiary of the Domestic Food Corporation.\"" },
  { english: "cologne", hebrew: "קלן", example: "Do I have to sit downwind of Georgie's cologne?" },
  { english: "bum", hebrew: "בטלן", example: "There's a bum sleeping on our front porch." },
  { english: "porch", hebrew: "המרפסת", example: "There's a bum sleeping on our front porch." },
  { english: "mow", hebrew: "לכסח", example: "Why haven't you mowed the lawn?" },
  { english: "beverage", hebrew: "משקה", example: "Can I offer you a hot beverage?" },
  { english: "bonehead", hebrew: "טֶמבֶּל", example: "You're not an idiot. You're just a bonehead." },
  { english: "dump", hebrew: "לזרוק", example: "Kind of a dump." },
  { english: "homicide", hebrew: "רצח", example: "\"or seller's agent must disclose if a homicide" },
  { english: "slingshot", hebrew: "קלע", example: "is called the slingshot." },
  { english: "toe", hebrew: "בהונות", example: "flashing your toes at me." },
  { english: "flickering", hebrew: "הִבהוּב", example: "with a flickering light." },
  { english: "chest", hebrew: "חזה", example: "In the center of the room is a mysterious glowing chest." },
  { english: "sock", hebrew: "גרב", example: "Why was there a sock on your door?" },
  { english: "pry", hebrew: "לְחַטֵט", example: "-Shall I pry? -Uh, it's nothing." },
  { english: "waist", hebrew: "המותניים", example: "OR THE WAIST DOWN." },
  { english: "commencement", hebrew: "התחלה", example: "IN THE MIDDLE OF THE COMMENCEMENT ADDRESS." },
  { english: "flan", hebrew: "פלאן", example: "WE'RE HAVING BIRTHDAY FLAN." },
  { english: "goon", hebrew: "גון", example: "BECAUSE THAT'S WHERE THE PARTY IS, YOU GOON." },
  { english: "volleyball", hebrew: "כדורעף", example: "QUICK VOLLEYBALL QUESTION." },
  { english: "scotch", hebrew: "וויסקי", example: "WITH YOUR SCOTCH ON THE ROCKS IN A GLASS." },
  { english: "chimney", hebrew: "ארובה", example: "YEAH, LIKE A CHIMNEY." },
  { english: "moisten", hebrew: "לְרַטֵּט", example: "I WAS JUST MOISTENING THE TIP." },
  { english: "regiment", hebrew: "מְסוּדָּר", example: "ON A CAREFULLY REGIMENTED PROGRAM OF DENIAL..." },
  { english: "forefather", hebrew: "אבות", example: "OUR FOREFATHERS USED TO BITCH AT EACH OTHER?" },
  { english: "fabulous", hebrew: "נפלא", example: "YOU LOOK FABULOUS, HONEY, YOU REALLY DO." },
  { english: "rub", hebrew: "שפשף", example: "AND RUB THEM ALL OVER MY BODY." },
  { english: "phony", hebrew: "מְזוּיָף", example: "WHAT A PHONY." },
  { english: "quippy", hebrew: "מהנה", example: "I TEND TO GET A LITTLE DEFENDED AND QUIPPY?" },
  { english: "bassinet", hebrew: "סַלְטָר", example: "DO YOU SEE A LITTLE BASSINET IN THE CORNER?" },
  { english: "hound", hebrew: "כלבם", example: "LIKE A HOUND?" },
  { english: "hovercraft", hebrew: "רחפת", example: "I'M TALKING HOVERCRAFTS" },
  { english: "ap", hebrew: "ap", example: "AND APES TAKING OVER THE PLANET." },
  { english: "crawl", hebrew: "זחל", example: "I SAW THE WINDOW THAT I CRAWLED OUT OF AT MY WEDDING" },
  { english: "bridesmaid", hebrew: "השושבינות", example: "IT'S TIME. BRIDESMAIDS AND USHERS..." },
  { english: "usher", hebrew: "שומרים", example: "IT'S TIME. BRIDESMAIDS AND USHERS..." },
  { english: "syphilis", hebrew: "עגבת", example: "FROM THE SYPHILIS." },
  { english: "courage", hebrew: "אומץ", example: "THAT IT DID TAKE A LOT OF COURAGE" },
  { english: "wink", hebrew: "הִקְרִיץ", example: "THAT GIRL TOTALLY WINKED AT ME." },
  { english: "terrace", hebrew: "מרפסת", example: "OUT ON THE TERRACE..." },
  { english: "squeaky", hebrew: "צְרוּפִית", example: "AND ALL I COULD HEAR WAS LIKE THIS HIGH SQUEAKY SOUND" },
  { english: "blinking", hebrew: "מהבהב", example: "YOU LOOK ME IN THE EYE AND TELL ME WITHOUT BLINKING" },
  { english: "drain", hebrew: "לנקז", example: "OH, GOD, LOOK WHAT I FOUND IN THE DRAIN." },
  { english: "staring", hebrew: "בוהה", example: "STARING AT A PARKING METER." },
  { english: "meadow", hebrew: "מדו", example: "ALL RIGHT, SO, YOU'RE IN A MEADOW" },
  { english: "brook", hebrew: "פלג", example: "AND THE CALMING SOUNDS OF THE BABBLING BROOK..." },
  { english: "babbling", hebrew: "שְׂפַת־סָפָה", example: "AND THE CALMING SOUNDS OF THE BABBLING BROOK..." },
  { english: "cuddly", hebrew: "חמוד", example: "I THOUGHT YOU GUYS WERE CUDDLY SLEEPY." },
  { english: "drift", hebrew: "להיסחף", example: "TO DRIFT OFF, AND THEN YOU HUG HER" },
  { english: "dingy", hebrew: "מְלוּכָּלָה", example: "OLD AND DINGY, THAT'S ALL." },
  { english: "melt", hebrew: "התכה", example: "OKAY, SO, BY \"MELTING\" YOU MEANT MELTING." },
  { english: "fume", hebrew: "אדים", example: "I THINK THE FUMES ARE GIVING ME A HEADACHE." },
  { english: "charming", hebrew: "מקסים", example: "WELL, HE'S VERY CHARMING." },
  { english: "soberly", hebrew: "בְּצִנּוּת", example: "THAT I WOULD NEVER SOBERLY HURT YOU OR YOUR FAMILY." },
  { english: "eavesdropping", hebrew: "ציתות", example: "EAVESDROPPING? PHEEBS, THE CEILING TILES" },
  { english: "turtle", hebrew: "צבים", example: "TURTLES SCARE ME." },
  { english: "stripper", hebrew: "חשפנית", example: "IS SO HE CAN SEE A STRIPPER." },
  { english: "abridgment", hebrew: "קיצור", example: "THE ABRIDGEMENT." },
  { english: "goof", hebrew: "שִׁחְקוּק", example: "Oh, he's just goofing around." },
  { english: "vase", hebrew: "אגרטל", example: "\"THE EMPTY VASE." },
  { english: "translucent", hebrew: "שקוף", example: "TRANSLUCENT BEAUTY...\"" },
  { english: "confidante", hebrew: "סודנית", example: "HE'S BECOMING HER CONFIDANTE." },
  { english: "dense", hebrew: "צפוף", example: "WERE REALLY DENSE ABOUT POETRY?" },
  { english: "eclipse", hebrew: "כיסוי", example: "LIKE AN ECLIPSE." },
  { english: "log", hebrew: "יומן רישום", example: "OR AT LEAST WHAT I THOUGHT WAS A LOG." },
  { english: "trail", hebrew: "שביל", example: "YOU ALWAYS HAVE TO THINK ABOUT THE TRAIL!" },
  { english: "chop", hebrew: "קְצַת", example: "AND COULD YOU PLEASE CHOP SOME UP" },
  { english: "sauce", hebrew: "רוטב", example: "AND PUT IT RIGHT IN THE SAUCE?" },
  { english: "wire", hebrew: "חוט", example: "THE UNDER-WIRE FROM YOUR BRA." },
  { english: "loon", hebrew: "פריגטה", example: "OKAY, UM, YOU'RE A LOON, YOU KNOW?" },
  { english: "cranky", hebrew: "עצבני", example: "SHE WAS A CRUEL, CRANKY, OLD BITCH." },
  { english: "barrel", hebrew: "חבית", example: "WHEN I WAS A KID, I HAD A BARREL." },
  { english: "attic", hebrew: "עליית גג", example: "THAT'S THE GHOST FOR THE ATTIC." },
  { english: "sedative", hebrew: "תרופה מרגיעה", example: "TAKE A SEDATIVE." },
  { english: "maintenance", hebrew: "תחזוקה", example: "IS JUST, YOU KNOW, YOU'RE... KIND OF HIGH MAINTENANCE." },
  { english: "spat", hebrew: "ריב", example: "I THINK OUR LOVERS' SPAT" },
  { english: "bid", hebrew: "הצעה", example: "and then the highest bid gets it." },
  { english: "stepdad", hebrew: "אבא חורג", example: "and my stepdad would drag me around the backyard." },
  { english: "corny", hebrew: "נדוש", example: "Don't be so corny, Ross." },
  { english: "reindeer", hebrew: "אייל צפוני", example: "Santa has reindeers that can fly." },
  { english: "crib", hebrew: "עריסה", example: "Step away from the crib!" },
  { english: "stirring", hebrew: "לזוז", example: "Well, I heard Emma stirring," },
  { english: "blimp", hebrew: "ספינת אוויר", example: "Oh, please. Hit by a blimp?" },
  { english: "throw", hebrew: "להיזרק", example: "Sorry. I guess I was thrown off by the mention of my name." },
  { english: "pigeon", hebrew: "יונה", example: "and then a pigeon ate it." },
  { english: "grief", hebrew: "צער", example: "This about people not having a decent outlet for their grief." },
  { english: "fungus", hebrew: "פטריה", example: "Mucus, fungus, and the idea of me and Ross doing it." },
  { english: "mucus", hebrew: "נזלת", example: "Mucus, fungus, and the idea of me and Ross doing it." },
  { english: "oversee", hebrew: "לפקח", example: "to oversee all the kissing!" },
  { english: "haunted", hebrew: "רדוף", example: "some people are going to get seriously haunted." },
  { english: "mourner", hebrew: "מתאבל", example: "Oh, this is so exciting, my first mourner." },
  { english: "strain", hebrew: "להתאמץ", example: "He strained his eyes by reading too much." },
  { english: "skittish", hebrew: "עצבני", example: "So excuse me for being a little skittish." },
  { english: "sweetheart", hebrew: "יקירי/יקירתי", example: "Good night, sweetheart. I love you." },
  { english: "wishbone", hebrew: "עצם משאלות", example: "Well, before, with the wishbone..." },
  { english: "beg", hebrew: "להתחנן", example: "I beg to differ." },
  { english: "lottery", hebrew: "לוטו", example: "Oh, the Powerball Lottery is up to $300 million" },
  { english: "pitch", hebrew: "להשתתף", example: "Why don't we all pitch in 50 bucks," },
  { english: "vanish", hebrew: "להיעלם", example: "The woman just vanished." },
  { english: "odd", hebrew: "סיכוי", example: "No. Do you know what your odds are of winning the lottery?" },
  { english: "tow", hebrew: "לגרור", example: "They're towing your car!" },
  { english: "casserole", hebrew: "תבשיל קדירה", example: "She dropped off a casserole." },
  { english: "piss", hebrew: "לבזבז", example: "I meant be cool and piss it all away." },
  { english: "spank", hebrew: "להעניש", example: "Is Daddy going to spank me?" },
  { english: "nightstand", hebrew: "שידת לילה", example: "There are no tickets on the nightstand." },
  { english: "bond", hebrew: "אג\"ח", example: "I'm going to put it all into a very low-yield bond." },
  { english: "squished", hebrew: "מעוך", example: "Valuable things are getting squished." },
  { english: "bra", hebrew: "חזייה", example: "Even these five that I hid in my bra." },
  { english: "cantaloupe", hebrew: "מלון קנטלופ", example: "but I think a cantaloupe might hurt less." },
  { english: "rehearse", hebrew: "לחזור על", example: "I'm rehearsing my lines." },
  { english: "inn", hebrew: "פונדק", example: "I'm taking Monica to a romantic inn in Vermont." },
  { english: "gorgeous", hebrew: "מדהים", example: "He is so gorgeous." },
  { english: "superb", hebrew: "מעולה", example: "The duck in particular was superb." },
  { english: "spleen", hebrew: "טחול", example: "♪ You can buy a human spleen ♪" },
  { english: "entertain", hebrew: "לבדר", example: "so I'm here to entertain." },
  { english: "dungeon", hebrew: "צינוק", example: "He was keeping my sister in a dungeon.\"" },
  { english: "complimentary", hebrew: "במתנה", example: "Could-could you have some complimentary toiletries" },
  { english: "toiletry", hebrew: "כלי רחצה", example: "Could-could you have some complimentary toiletries" },
  { english: "mouthwash", hebrew: "מי פה", example: "razor, mouthwash, deodorant," },
  { english: "razor", hebrew: "סכין גילוח", example: "razor, mouthwash, deodorant," },
  { english: "pepper", hebrew: "פלפל", example: "these great salt and pepper shakers" },
  { english: "shaker", hebrew: "מלחייה/פלפליה", example: "these great salt and pepper shakers" },
  { english: "think", hebrew: "לחשוב", example: "I wish I'd thought this through." },
  { english: "vault", hebrew: "כספת", example: "I'll ask the butler to fetch my diamonds out of the vault." },
  { english: "pretentious", hebrew: "יומרני", example: "your tiny portions of pretentious food?" },
  { english: "appetizer", hebrew: "מנה ראשונה", example: "\"I ordered the smoked salmon appetizer." },
  { english: "plug", hebrew: "אטם", example: "I'm wearing ear plugs." },
  { english: "clove", hebrew: "ציפורן", example: "Ear plugs? Or cloves of garlic?" },
  { english: "cone", hebrew: "אצטרובל", example: "But I-I want... I want the pine cones." },
  { english: "pretension", hebrew: "ימרנות", example: "and a little pretension never hurt anyone?" },
  { english: "incessant", hebrew: "בלתי פוסק", example: "but your evening was ruined by this incessant poll taking?" },
  { english: "peanut", hebrew: "בוטנים", example: "do you have peanut butter on the back of your head?" },
  { english: "butter", hebrew: "חמאת בוטנים", example: "do you have peanut butter on the back of your head?" },
  { english: "insemination", hebrew: "הזרעה", example: "the only other choice is insemination," },
  { english: "sperm", hebrew: "זרע", example: "so we're talking about sperm donors." },
  { english: "coaster", hebrew: "תחתיות", example: "Do you... do you have a coaster?" },
  { english: "tan", hebrew: "להשתזף", example: "Look at that woman sitting out by the pool getting tan." },
  { english: "clunk", hebrew: "להטיח", example: "I clunked your heads together." },
  { english: "non-racquet", hebrew: "יד לא אוחזת מחבט", example: "if at any time a player uses his non-racquet-bearing hand" },
  { english: "forfeit", hebrew: "לוותר", example: "to touch the playing surface, he or she forfeits the point." },
  { english: "musing", hebrew: "הרהור", example: "Musings, if you will." },
  { english: "eavesdrop", hebrew: "להקשיב בסתר", example: "I'm not going to eavesdrop on my friend." },
  { english: "bedspring", hebrew: "קפיץ מיטה", example: "Bedsprings... unmistakable." },
  { english: "enunciate", hebrew: "להגות", example: "Enunciate." },
  { english: "shellfish", hebrew: "רכיכות", example: "Y-You got shellfish in your head." },
  { english: "rattling", hebrew: "רעש", example: "( shells rattling )" },
  { english: "hum", hebrew: "לזמזם", example: "( humming )" },
  { english: "skull", hebrew: "גולגולת", example: "the shape of your skull before." },
  { english: "endeavor", hebrew: "מאמץ", example: "and wishes you the best of luck in all your endeavors." },
  { english: "wang", hebrew: "וואנג", example: "and let's face it, Mike's kind of a wang." },
  { english: "gnaw", hebrew: "לכרסם", example: "Yeah, I tried to gnaw myself free." },
  { english: "untangle", hebrew: "להתיר", example: "Now that I untangled you," },
  { english: "malfunctioning", hebrew: "תקלה", example: "So, a lot of malfunctioning wee-wees and hoo-hoos in this room, huh?" },
  { english: "raging", hebrew: "זועם", example: "My father is a raging alcoholic." },
  { english: "mitt", hebrew: "כפפה", example: "Ross, you don't even have oven mitts on." },
  { english: "sake", hebrew: "למען", example: "Well, just, you know, for argument's sake," },
  { english: "burp", hebrew: "גיהוק", example: "She's, she's the only one that knows how to burp the alphabet." },
  { english: "mug", hebrew: "ספל", example: "Here, I heated up a nice hot mug of Diet Coke for you." },
  { english: "splinter", hebrew: "שבור", example: "on his splintered office floor." },
  { english: "crest", hebrew: "סמל", example: "with the crests on them." },
  { english: "stipulate", hebrew: "לקבוע", example: "Because the contract stipulates we're not allowed to release" },
  { english: "ascent", hebrew: "נסיקה", example: "Diane watched as the sun made its ascent on the horizon." },
];
